{{- if and .Values.monitor.enabled .Values.monitor.service.enabled .Values.monitor.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "agent-bom.name" . }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-bom.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitor
    {{- with .Values.monitor.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.monitor.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "agent-bom.name" . }}
      app.kubernetes.io/component: monitor
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: protect
      path: /metrics
      interval: {{ .Values.monitor.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitor.serviceMonitor.scrapeTimeout }}
{{- end }}
