{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-bom.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-bom.labels" . | nindent 4 }}
{{- end }}
