// Next Proxy is server-only. Generate its entry point only for server builds.
import { writeFileSync, rmSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const uiRoot = fileURLToPath(new URL("../", import.meta.url));
const entry = new URL("../proxy.ts", import.meta.url);
if (process.env.NEXT_EXPORT === "1") {
  rmSync(entry, { force: true });
} else {
  writeFileSync(entry, `// Generated by scripts/run-next.mjs; excluded from static exports.
export { proxyApiRequest as proxy } from "./server/runtime-api-proxy";
export const config = { matcher: ["/v1/:path*", "/health", "/version", "/ws/:path*"] };
`);
}
const require = createRequire(import.meta.url);
const result = spawnSync(process.execPath, [require.resolve("next/dist/bin/next"), ...process.argv.slice(2)], {
  cwd: uiRoot, env: process.env, stdio: "inherit",
});
if (result.error) {
  console.error("Unable to start Next.js");
  process.exit(1);
}
process.exit(result.status ?? 1);
