"""Vanta integration — upload compliance evidence.

Vanta is a GRC platform. This uploads scan results as evidence
for SOC 2/ISO 27001/HIPAA compliance.

Uses the Vanta REST API — no SDK dependency.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Optional

from agent_bom.http_client import create_client, request_with_retry

logger = logging.getLogger(__name__)

VANTA_API_URL = "https://api.vanta.com"


async def upload_evidence(
    token: str,
    scan_result: dict,
    evidence_name: str = "agent-bom AI Supply Chain Scan",
) -> Optional[str]:
    """Upload agent-bom scan results as Vanta compliance evidence.

    Args:
        token: Vanta API bearer token
        scan_result: Full JSON scan result from agent-bom
        evidence_name: Human-readable evidence name

    Returns:
        Evidence ID or None on failure.
    """
    total_vulns = scan_result.get("summary", {}).get("total_vulnerabilities", 0)
    total_agents = scan_result.get("summary", {}).get("total_agents", 0)
    critical_count = sum(
        1 for br in scan_result.get("blast_radius", [])
        if br.get("severity") == "critical"
    )

    payload = {
        "name": evidence_name,
        "description": (
            f"Automated AI supply chain security scan. "
            f"Scanned {total_agents} agent(s), found {total_vulns} vulnerability(ies) "
            f"({critical_count} critical). "
            f"Generated by agent-bom v{scan_result.get('tool_version', '?')}"
        ),
        "collected_at": datetime.now(timezone.utc).isoformat(),
        "metadata": {
            "tool": "agent-bom",
            "version": scan_result.get("tool_version", ""),
            "total_agents": total_agents,
            "total_vulnerabilities": total_vulns,
            "critical_vulnerabilities": critical_count,
            "compliance_frameworks": ["OWASP LLM Top 10", "OWASP MCP Top 10", "MITRE ATLAS", "NIST AI RMF"],
        },
    }

    url = f"{VANTA_API_URL}/v1/evidence"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    async with create_client(timeout=15.0) as client:
        response = await request_with_retry(
            client, "POST", url, json_body=payload, headers=headers, max_retries=2,
        )

        if response and response.status_code in (200, 201):
            data = response.json()
            evidence_id = data.get("id", "")
            logger.info("Vanta evidence uploaded: %s", evidence_id)
            return evidence_id

        status = response.status_code if response else "no response"
        logger.warning("Vanta evidence upload failed: %s", status)
        return None
