"""README commands must be runnable on a clean checkout.

The README is the first command most people ever run. A documented invocation
that names a file the repo never ships and no documented command creates fails
before it starts (`Error: Invalid value for '--upstreams': File 'upstreams.yaml'
does not exist.`). This guard reads the click tree — not a hand-maintained list
— so the whole class of defect fails CI instead of a user's terminal.
"""

from __future__ import annotations

import re
import shlex
from pathlib import Path
from typing import Any

import click

from agent_bom.cli import main

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"

# The first-run surfaces: what someone runs before they know anything else.
# `examples/` was outside this guard, so its README taught `--no-update-db` — a
# flag that has never existed (the real one is `--no-auto-update-db`) — and the
# documented first-run command died at argument parsing.
FIRST_RUN_DOCS: tuple[Path, ...] = (README, *sorted((ROOT / "examples").rglob("*.md")))

# Documentation placeholders, not literal paths.
_PLACEHOLDER = re.compile(r"^[<$]|[<>{}*]|^\.\.\.$")


def _iter_readme_invocations(text: str) -> list[list[str]]:
    """Return tokenized `agent-bom …` invocations found in the README."""
    invocations: list[list[str]] = []
    for raw_line in text.splitlines():
        # Markdown tables and inline code wrap commands in `|` and backticks.
        for snippet in re.findall(r"agent-bom [^`|\n]+", raw_line):
            snippet = snippet.strip().rstrip("\\").strip()
            try:
                tokens = shlex.split(snippet)
            except ValueError:
                continue
            if len(tokens) > 1:
                invocations.append(tokens)
    return invocations


def _resolve(tokens: list[str]) -> tuple[click.Command | None, list[str]]:
    """Walk the click tree for `agent-bom sub sub …`, returning the command + rest."""
    command: click.Command = main
    index = 1  # tokens[0] is the "agent-bom" executable name
    while index < len(tokens) and isinstance(command, click.Group):
        child = command.get_command(click.Context(command), tokens[index])
        if child is None:
            break
        command = child
        index += 1
    return (None if command is main else command), tokens[index:]


def _required_existing_path_options(command: click.Command) -> dict[str, click.Parameter]:
    options: dict[str, click.Parameter] = {}
    for param in command.params:
        param_type = getattr(param, "type", None)
        if isinstance(param_type, click.Path) and getattr(param_type, "exists", False):
            for opt in getattr(param, "opts", []):
                options[opt] = param
    return options


def _generated_filenames() -> set[str]:
    """Default output filenames that some `agent-bom` command writes."""
    generated: set[str] = set()

    def walk(command: click.Command) -> None:
        if isinstance(command, click.Group):
            for child in command.commands.values():
                walk(child)
            return
        for param in command.params:
            if not set(getattr(param, "opts", [])) & {"--output", "--target", "-o"}:
                continue
            default: Any = getattr(param, "default", None)
            if default in (None, ""):
                continue
            generated.add(Path(str(default)).name)

    walk(main)
    return generated


def test_readme_commands_only_reference_files_that_exist_or_are_generated() -> None:
    readme = README.read_text(encoding="utf-8")
    generated = _generated_filenames()
    unrunnable: list[str] = []

    for tokens in _iter_readme_invocations(readme):
        command, rest = _resolve(tokens)
        if command is None:
            continue
        path_options = _required_existing_path_options(command)
        for position, token in enumerate(rest):
            option, _, inline_value = token.partition("=")
            param = path_options.get(option)
            if param is None:
                continue
            value = inline_value or (rest[position + 1] if position + 1 < len(rest) else "")
            if not value or _PLACEHOLDER.search(value):
                continue
            name = Path(value).name
            if (ROOT / value).exists() or name in generated:
                continue
            unrunnable.append(f"{' '.join(tokens)} — {option} {value!r} is neither shipped nor generated by a documented command")

    assert unrunnable == [], "README teaches commands that cannot run on a clean checkout:\n" + "\n".join(unrunnable)


def _known_options(command: click.Command) -> set[str]:
    """Every option spelling click will accept for *command*."""
    options: set[str] = {"--help", "-h"}
    for param in command.params:
        options.update(getattr(param, "opts", []))
        options.update(getattr(param, "secondary_opts", []))
    return options


def _join_continuations(text: str) -> str:
    """Fold `\\`-continued shell commands onto one line.

    Without this the scan sees only the first line of a multi-line invocation,
    which is exactly where the `--no-update-db` defect hid: the flag sat four
    continuation lines below `agent-bom agents \\`.
    """
    return re.sub(r"\\\n\s*", " ", text)


def test_first_run_docs_only_use_options_that_exist() -> None:
    """Every flag taught by a first-run doc must exist on that click command."""
    unknown: list[str] = []

    for doc in FIRST_RUN_DOCS:
        if not doc.exists():
            continue
        rel = doc.relative_to(ROOT)
        for tokens in _iter_readme_invocations(_join_continuations(doc.read_text(encoding="utf-8"))):
            command, rest = _resolve(tokens)
            if command is None:
                continue
            options = _known_options(command)
            for token in rest:
                option = token.partition("=")[0]
                # `--` ends option parsing; placeholders are documentation, not flags.
                if not option.startswith("-") or option == "--" or _PLACEHOLDER.search(option):
                    continue
                if option in options:
                    continue
                unknown.append(f"{rel}: `{' '.join(tokens)}` — {command.name} has no option {option}")

    assert unknown == [], "first-run docs teach flags that do not exist:\n" + "\n".join(unknown)


def test_readme_gateway_lane_starts_from_control_plane_discovery() -> None:
    """The gateway first command must not require a YAML the reader does not have.

    The only shipped upstreams file is an operator-authored Helm example with
    placeholder hosts and token env vars, and a `pip install` reader has no repo
    checkout, so `--upstreams <file>` cannot be the documented starting point.
    """
    readme = README.read_text(encoding="utf-8")

    assert "gateway serve --from-control-plane" in readme
    assert "gateway serve --upstreams" not in readme
