"""Runtime MCP registrations with per-server dispatch bindings."""

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from .bindings import OperatorToolBindings


def register_runtime_correlate(bindings: OperatorToolBindings) -> None:
    from agent_bom.mcp_tools.runtime import runtime_correlate_impl

    mcp = bindings.mcp

    @mcp.tool(annotations=bindings.read_only, title="Runtime Correlation")
    async def runtime_correlate(
        config_path: Annotated[
            str,
            Field(description="Path to MCP config directory (e.g. ~/.config/claude) or 'auto' for default discovery."),
        ] = "auto",
        audit_log: Annotated[
            str,
            Field(description="Path to proxy audit JSONL log file (generated by 'agent-bom proxy --log audit.jsonl')."),
        ] = "",
        otel_trace: Annotated[
            str,
            Field(description="Path to OTel OTLP JSON trace file for ML API provenance (detects deprecated/vulnerable model versions)."),
        ] = "",
    ) -> str:
        """Cross-reference vulnerability scan results with proxy runtime audit logs.

        Identifies which vulnerable tools were ACTUALLY CALLED in production,
        distinguishing confirmed attack surface from theoretical risk. Produces
        risk-amplified findings: a vulnerable tool that was called 100 times is
        higher priority than one never invoked.

        Also accepts an OTel trace file (``otel_trace``) to extract ML API call
        provenance: which models were called, token usage, and deprecation advisories.

        Requires a proxy audit log (generated by running agent-bom proxy with
        the --log flag). Without an audit log, returns scan results only.

        Returns:
            JSON with correlated findings (CVE + tool call data + amplified risk),
            summary stats, uncalled vulnerable tools, and ml_api_calls provenance.
        """
        return await bindings.execute_tool_async(
            "runtime_correlate",
            runtime_correlate_impl,
            config_path=config_path,
            audit_log=audit_log,
            otel_trace=otel_trace,
            _safe_path=bindings.safe_path,
            _run_scan_pipeline=bindings.run_scan_pipeline,
            _truncate_response=bindings.truncate_response,
        )


def register_runtime_production_index(bindings: OperatorToolBindings) -> None:
    from agent_bom.mcp_tools.runtime import runtime_production_index_impl

    mcp = bindings.mcp

    @mcp.tool(annotations=bindings.read_only, title="Runtime Production Index")
    async def runtime_production_index(
        tenant_id: Annotated[
            str,
            Field(description="Tenant scope to summarize. Defaults to the control-plane default tenant."),
        ] = "default",
    ) -> str:
        """Return metadata-only runtime production posture for agent/tool traffic.

        Summarizes tool-call volume, block rate, policy decisions, authorization
        trace posture, alerts, active sources/sessions, freshness, and retention
        mode without returning prompts, raw arguments, responses, or credential
        values.
        """
        return await bindings.execute_tool_async(
            "runtime_production_index",
            runtime_production_index_impl,
            tenant_id=tenant_id,
            _truncate_response=bindings.truncate_response,
        )


def register_runtime_blueprints(bindings: OperatorToolBindings) -> None:
    from agent_bom.mcp_tools.runtime import runtime_blueprints_impl

    mcp = bindings.mcp

    @mcp.tool(annotations=bindings.read_only, title="Runtime Blueprints")
    async def runtime_blueprints(
        blueprint_id: Annotated[
            str,
            Field(description="Optional blueprint id such as developer, security_analyst, mlops, finance, or admin."),
        ] = "",
        tenant_id: Annotated[
            str,
            Field(description="Tenant scope for the response envelope."),
        ] = "default",
    ) -> str:
        """Return canonical role/profile blueprints for runtime policy design."""
        return await bindings.execute_tool_async(
            "runtime_blueprints",
            runtime_blueprints_impl,
            blueprint_id=blueprint_id,
            tenant_id=tenant_id,
            _truncate_response=bindings.truncate_response,
        )


def register_runtime_blueprint_drift(bindings: OperatorToolBindings) -> None:
    from agent_bom.mcp_tools.runtime import runtime_blueprint_drift_impl

    mcp = bindings.mcp

    @mcp.tool(annotations=bindings.read_only, title="Runtime Blueprint Drift")
    async def runtime_blueprint_drift(
        blueprint_id: Annotated[
            str,
            Field(description="Blueprint id to evaluate, such as developer, security_analyst, mlops, finance, or admin."),
        ],
        tenant_id: Annotated[
            str,
            Field(description="Tenant scope to summarize. Defaults to the control-plane default tenant."),
        ] = "default",
    ) -> str:
        """Compare current runtime traffic with an approved role/profile blueprint."""
        return await bindings.execute_tool_async(
            "runtime_blueprint_drift",
            runtime_blueprint_drift_impl,
            blueprint_id=blueprint_id,
            tenant_id=tenant_id,
            _truncate_response=bindings.truncate_response,
        )


def register_cost_report(bindings: OperatorToolBindings) -> None:
    from agent_bom.mcp_tools.runtime import cost_report_impl

    mcp = bindings.mcp

    @mcp.tool(annotations=bindings.read_only, title="Cost Report")
    async def cost_report(
        agent: Annotated[
            str,
            Field(description="Optional agent name to scope spend to a single agent."),
        ] = "",
        tenant_id: Annotated[
            str,
            Field(description="Tenant scope to summarize. Defaults to the control-plane default tenant."),
        ] = "default",
    ) -> str:
        """Return LLM spend attribution (per agent/model/provider) and budget posture.

        Spend is derived from token counts on ingested OpenTelemetry GenAI spans
        priced via agent-bom's open cost model; no prompts or responses are read.
        """
        return await bindings.execute_tool_async(
            "cost_report",
            cost_report_impl,
            agent=agent,
            tenant_id=tenant_id,
            _truncate_response=bindings.truncate_response,
        )


def register_anomaly_scan(bindings: OperatorToolBindings) -> None:
    from agent_bom.mcp_tools.runtime import anomaly_scan_impl

    mcp = bindings.mcp

    @mcp.tool(annotations=bindings.read_only, title="Anomaly Scan")
    async def anomaly_scan(
        z_threshold: Annotated[
            float,
            Field(description="Z-score threshold for flagging an outlier (default 3.0; higher = stricter)."),
        ] = 3.0,
        tenant_id: Annotated[
            str,
            Field(description="Tenant scope to summarize. Defaults to the control-plane default tenant."),
        ] = "default",
    ) -> str:
        """Surface cost and behavior anomalies: per-agent spend and per-session
        tool-call-rate statistical outliers, for proactive runaway-agent detection."""
        return await bindings.execute_tool_async(
            "anomaly_scan",
            anomaly_scan_impl,
            z_threshold=z_threshold,
            tenant_id=tenant_id,
            _truncate_response=bindings.truncate_response,
        )


def register_drift_incidents(bindings: OperatorToolBindings) -> None:
    from agent_bom.mcp_tools.runtime import drift_incidents_impl

    mcp = bindings.mcp

    @mcp.tool(annotations=bindings.read_only, title="Drift Incidents")
    async def drift_incidents(
        include_resolved: Annotated[
            bool,
            Field(description="Include resolved incidents. Defaults to open incidents only."),
        ] = False,
        tenant_id: Annotated[
            str,
            Field(description="Tenant scope to summarize. Defaults to the control-plane default tenant."),
        ] = "default",
    ) -> str:
        """List open blueprint-drift incidents (observed runtime traffic outside the approved role blueprint).

        Each incident records the blueprint, drift score, and top violations so an
        operator can reconcile the agent or blueprint and resolve it.
        """
        return await bindings.execute_tool_async(
            "drift_incidents",
            drift_incidents_impl,
            include_resolved=include_resolved,
            tenant_id=tenant_id,
            _truncate_response=bindings.truncate_response,
        )


def register_proxy_status(bindings: OperatorToolBindings) -> None:
    from agent_bom.mcp_tools.runtime import proxy_status_impl

    mcp = bindings.mcp

    @mcp.tool(annotations=bindings.read_only, title="Proxy Status")
    async def proxy_status(
        tenant_id: Annotated[
            str,
            Field(description="Tenant scope to summarize. Defaults to the control-plane default tenant."),
        ] = "default",
    ) -> str:
        """Return current MCP proxy metrics and alert summary, if a session is active."""
        return await bindings.execute_tool_async(
            "proxy_status",
            proxy_status_impl,
            tenant_id=tenant_id,
            _truncate_response=bindings.truncate_response,
        )


def register_proxy_alerts(bindings: OperatorToolBindings) -> None:
    from agent_bom.mcp_tools.runtime import proxy_alerts_impl

    mcp = bindings.mcp

    @mcp.tool(annotations=bindings.read_only, title="Proxy Alerts")
    async def proxy_alerts(
        tenant_id: Annotated[
            str,
            Field(description="Tenant scope to read. Defaults to the control-plane default tenant."),
        ] = "default",
        severity: Annotated[
            str,
            Field(description="Optional severity filter: critical, high, medium, low, or info."),
        ] = "",
        detector: Annotated[
            str,
            Field(description="Optional detector name filter, for example credential_leak."),
        ] = "",
        limit: Annotated[
            int,
            Field(ge=1, le=1000, description="Maximum alerts to return."),
        ] = 100,
    ) -> str:
        """Return recent runtime proxy alerts without prompts, arguments, or responses."""
        return await bindings.execute_tool_async(
            "proxy_alerts",
            proxy_alerts_impl,
            tenant_id=tenant_id,
            severity=severity,
            detector=detector,
            limit=limit,
            _truncate_response=bindings.truncate_response,
        )


def register_gateway_status(bindings: OperatorToolBindings) -> None:
    from agent_bom.mcp_tools.runtime import gateway_status_impl

    mcp = bindings.mcp

    @mcp.tool(annotations=bindings.read_only, title="Gateway Status")
    async def gateway_status(
        tenant_id: Annotated[
            str,
            Field(description="Tenant scope to summarize. Defaults to the control-plane default tenant."),
        ] = "default",
        include_activity: Annotated[
            bool,
            Field(description="Include the durable, cursor-paged gateway activity feed."),
        ] = False,
        activity_limit: Annotated[
            int,
            Field(ge=1, le=500, description="Maximum activity events to return when include_activity is true."),
        ] = 100,
        activity_cursor: Annotated[
            str,
            Field(description="Opaque cursor from a prior gateway_status activity response."),
        ] = "",
        include_self_posture: Annotated[
            bool,
            Field(description="Include this deployment's tenant-scoped operator self-posture evidence."),
        ] = False,
    ) -> str:
        """Return gateway policy, firewall, durable activity, and optional self-posture evidence."""
        return await bindings.execute_tool_async(
            "gateway_status",
            gateway_status_impl,
            tenant_id=tenant_id,
            include_activity=include_activity,
            activity_limit=activity_limit,
            activity_cursor=activity_cursor,
            include_self_posture=include_self_posture,
            _truncate_response=bindings.truncate_response,
        )


REGISTRATIONS = (
    register_runtime_correlate,
    register_runtime_production_index,
    register_runtime_blueprints,
    register_runtime_blueprint_drift,
    register_cost_report,
    register_anomaly_scan,
    register_drift_incidents,
    register_proxy_status,
    register_proxy_alerts,
    register_gateway_status,
)
