"""Ready-to-run, read-only onboarding artifacts for ``agent-bom connect``.

``connect <provider>`` already brokers short-lived read-only credentials and
prints grant *instructions*. This module closes the last gap: it emits a single
ready-to-run *artifact* the operator can deploy as-is to provision the read-only
principal the connect flow then consumes.

Design invariants (all enforced by tests):

* **Read-only only.** Every artifact grants read/list/describe access — never a
  create/update/delete/admin permission. AWS uses the AWS-managed
  ``SecurityAudit`` + ``ViewOnlyAccess`` policies (the same baseline as
  ``deploy/terraform/connect-aws``); Azure uses the built-in ``Reader`` role;
  GCP uses ``roles/viewer`` (+ ``roles/iam.securityReviewer``); Snowflake creates
  a governance-metadata role with no DML/DDL.
* **No baked secrets.** The confused-deputy ``ExternalId`` is not a cryptographic
  secret (it is a shared correlation value that defeats the confused-deputy
  attack, not a credential), so it is emitted in the artifact — though when it is
  *supplied* to ``connect aws --external-id`` the CLI still stores it write-only
  by default, the conservative posture. Every actual secret (Azure client secret,
  GCP key, Snowflake key pair) is generated by the operator's own run and never
  written into the artifact.
* **Round-trip.** What the artifact provisions is exactly what
  ``connect <provider>`` consumes to establish + verify the connection.

Nothing here calls a cloud API — the functions are pure string builders.
"""

from __future__ import annotations

import json
import re
import secrets
from collections.abc import Mapping
from typing import Any

# AWS-managed read-only policies — the documented baseline, identical to the
# ``connect-aws`` Terraform module. Both are AWS-managed and grant no writes.
_AWS_MANAGED_POLICY_ARNS = [
    "arn:aws:iam::aws:policy/SecurityAudit",
    "arn:aws:iam::aws:policy/job-function/ViewOnlyAccess",
]

_AWS_ROLE_LOGICAL_ID = "AgentBomReadOnlyRole"

DEFAULT_AWS_ROLE_NAME = "agent-bom-readonly"
DEFAULT_AZURE_APP_NAME = "agent-bom-readonly"
DEFAULT_GCP_SERVICE_ACCOUNT = "agent-bom-readonly"
DEFAULT_SNOWFLAKE_ROLE = "AGENT_BOM_READONLY"
DEFAULT_SNOWFLAKE_USER = "AGENT_BOM_SVC"
DEFAULT_SNOWFLAKE_WAREHOUSE = "AGENT_BOM_WH"


def generate_external_id() -> str:
    """Return a high-entropy, URL/JSON-safe ExternalId (32 hex chars, 128 bits)."""
    return secrets.token_hex(16)


# ── input validation (injection defense) ───────────────────────────────────────
#
# These artifacts are interpolated into privileged, operator-run scripts (an
# ACCOUNTADMIN Snowflake script; ``set -euo pipefail`` bash). User-supplied names
# and ids MUST therefore be validated against a strict allowlist BEFORE
# interpolation — never quoted-and-hoped — so a hostile value is rejected with a
# clear error rather than silently corrupting the emitted script. Post-validation
# every accepted value is free of shell/SQL metacharacters by construction.

# Snowflake unquoted identifier: letter/underscore start, then
# letters/digits/underscore/dollar. Length capped at Snowflake's 255-char limit.
_SNOWFLAKE_IDENTIFIER_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_$]*")
_SNOWFLAKE_IDENTIFIER_MAX = 255

# Azure subscription id is always a GUID.
_AZURE_SUBSCRIPTION_RE = re.compile(r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")

# GCP project id / service-account id: lowercase-letter start, 6–30 chars total.
_GCP_ID_RE = re.compile(r"[a-z][a-z0-9-]{4,28}[a-z0-9]")

# Azure app display name: conservative allowlist (letters/digits/space/._-).
_AZURE_APP_NAME_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9 ._-]{0,119}")


def _validate_snowflake_identifier(value: str, *, field: str) -> str:
    if not _SNOWFLAKE_IDENTIFIER_RE.fullmatch(value) or len(value) > _SNOWFLAKE_IDENTIFIER_MAX:
        raise ValueError(
            f"invalid Snowflake {field} {value!r}: must be an unquoted identifier "
            f"matching [A-Za-z_][A-Za-z0-9_$]* (max {_SNOWFLAKE_IDENTIFIER_MAX} chars)"
        )
    return value


def _validate_azure_subscription_id(value: str) -> str:
    if value and not _AZURE_SUBSCRIPTION_RE.fullmatch(value):
        raise ValueError(f"invalid Azure subscription id {value!r}: expected a GUID (e.g. 00000000-0000-0000-0000-000000000000)")
    return value


def _validate_azure_app_name(value: str) -> str:
    if not _AZURE_APP_NAME_RE.fullmatch(value):
        raise ValueError(
            f"invalid Azure app name {value!r}: allowed characters are letters, digits, space, '.', '_' and '-' (max 120 chars)"
        )
    return value


def _validate_gcp_id(value: str, *, field: str) -> str:
    if value and not _GCP_ID_RE.fullmatch(value):
        raise ValueError(f"invalid GCP {field} {value!r}: must match [a-z][a-z0-9-]{{4,28}}[a-z0-9] (6–30 chars, lowercase)")
    return value


# ── AWS: CloudFormation ────────────────────────────────────────────────────────


def aws_cloudformation_template(
    *,
    external_id: str,
    role_name: str = DEFAULT_AWS_ROLE_NAME,
    trusted_principal_arn: str = "",
) -> str:
    """Return a CloudFormation template (JSON) that creates the read-only role.

    The role attaches only the AWS-managed ``SecurityAudit`` + ``ViewOnlyAccess``
    policies and can be assumed only by ``TrustedPrincipalArn`` presenting the
    enforced ``ExternalId``. ``RoleArn`` and ``ExternalId`` are exported as stack
    Outputs so they feed straight back into
    ``connect aws --role-arn <RoleArn> --external-id <ExternalId>``.

    ``trusted_principal_arn`` — when supplied — is baked as the parameter default
    so the stack is fully turnkey; otherwise the operator supplies it at deploy.
    """
    template: dict[str, Any] = {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": (
            "agent-bom read-only onboarding role (SecurityAudit + ViewOnlyAccess). "
            "Read-only: no create/update/delete permission is granted."
        ),
        "Parameters": {
            "TrustedPrincipalArn": {
                "Type": "String",
                "Default": trusted_principal_arn,
                "Description": ("ARN of the agent-bom scanner principal (account root or role) allowed to assume this read-only role."),
            },
            "ExternalId": {
                "Type": "String",
                "Default": external_id,
                "Description": (
                    "STS ExternalId enforced on assume-role (confused-deputy defense). Pass this to `agent-bom connect aws --external-id`."
                ),
            },
            "RoleName": {
                "Type": "String",
                "Default": role_name,
                "Description": "Name of the read-only IAM role to create.",
            },
        },
        "Resources": {
            _AWS_ROLE_LOGICAL_ID: {
                "Type": "AWS::IAM::Role",
                "Properties": {
                    "RoleName": {"Ref": "RoleName"},
                    "Description": ("Read-only role assumed by agent-bom (SecurityAudit + ViewOnlyAccess). No write permissions."),
                    "ManagedPolicyArns": list(_AWS_MANAGED_POLICY_ARNS),
                    "AssumeRolePolicyDocument": {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Effect": "Allow",
                                "Principal": {"AWS": {"Ref": "TrustedPrincipalArn"}},
                                "Action": "sts:AssumeRole",
                                "Condition": {"StringEquals": {"sts:ExternalId": {"Ref": "ExternalId"}}},
                            }
                        ],
                    },
                    "Tags": [
                        {"Key": "agent-bom.io/managed-by", "Value": "cloudformation"},
                        {"Key": "agent-bom.io/access", "Value": "read-only"},
                    ],
                },
            }
        },
        "Outputs": {
            "RoleArn": {
                "Description": "Pass to `agent-bom connect aws --role-arn`.",
                "Value": {"Fn::GetAtt": [_AWS_ROLE_LOGICAL_ID, "Arn"]},
            },
            "ExternalId": {
                "Description": "Pass to `agent-bom connect aws --external-id`.",
                "Value": {"Ref": "ExternalId"},
            },
        },
    }
    return json.dumps(template, indent=2)


# ── Azure: app registration + Reader assignment ────────────────────────────────


def azure_bootstrap_script(
    *,
    subscription_id: str = "",
    app_name: str = DEFAULT_AZURE_APP_NAME,
) -> str:
    """Return a bash script that creates a Reader service principal.

    Uses ``az ad sp create-for-rbac`` with the built-in **Reader** role scoped to
    the subscription — read-only, no write/delete. ``az`` prints the appId /
    tenant / client secret to the operator's own terminal at run time; the secret
    is never written into this artifact.
    """
    _validate_azure_subscription_id(subscription_id)
    _validate_azure_app_name(app_name)
    sub = subscription_id or "<YOUR_SUBSCRIPTION_ID>"
    return f"""#!/usr/bin/env bash
# agent-bom Azure read-only onboarding — creates a Reader service principal.
# Read-only: the built-in Reader role grants no write/delete permission.
# Run with an account that can create app registrations + role assignments.
set -euo pipefail

SUBSCRIPTION_ID="${{SUBSCRIPTION_ID:-{sub}}}"
APP_NAME="{app_name}"

# Create the app registration + service principal and assign built-in Reader.
# The client secret is printed once by az here — capture it now; it is never
# stored in this script.
CREDS="$(az ad sp create-for-rbac \\
  --name "$APP_NAME" \\
  --role "Reader" \\
  --scopes "/subscriptions/$SUBSCRIPTION_ID" \\
  --output json)"

APP_ID="$(echo "$CREDS" | python3 -c 'import sys,json;print(json.load(sys.stdin)["appId"])')"
TENANT_ID="$(echo "$CREDS" | python3 -c 'import sys,json;print(json.load(sys.stdin)["tenant"])')"
CLIENT_SECRET="$(echo "$CREDS" | python3 -c 'import sys,json;print(json.load(sys.stdin)["password"])')"

echo
echo "Reader service principal created. Establish the read-only connection with:"
echo
echo "  agent-bom connect azure \\"
echo "    --client-id $APP_ID \\"
echo "    --tenant-id $TENANT_ID \\"
echo "    --subscription-id {sub} \\"
echo "    --client-secret \\"$CLIENT_SECRET\\""
"""


# ── GCP: service account + roles/viewer binding ────────────────────────────────


def gcp_bootstrap_script(
    *,
    project_id: str = "",
    service_account: str = DEFAULT_GCP_SERVICE_ACCOUNT,
) -> str:
    """Return a bash script that creates a read-only viewer service account.

    Binds ``roles/viewer`` (+ ``roles/iam.securityReviewer``) at the project —
    both read-only. Workload Identity Federation is recommended; a key file is
    minted only when the operator opts in, and the key is written to their own
    disk, never into this artifact.
    """
    _validate_gcp_id(project_id, field="project id")
    _validate_gcp_id(service_account, field="service account id")
    proj = project_id or "<YOUR_PROJECT_ID>"
    return f"""#!/usr/bin/env bash
# agent-bom GCP read-only onboarding — creates a viewer service account.
# Read-only: roles/viewer + roles/iam.securityReviewer grant no write access.
set -euo pipefail

PROJECT_ID="${{PROJECT_ID:-{proj}}}"
SA_NAME="{service_account}"
SA_EMAIL="$SA_NAME@$PROJECT_ID.iam.gserviceaccount.com"

# 1. Create the service account.
gcloud iam service-accounts create "$SA_NAME" \\
  --project="$PROJECT_ID" \\
  --display-name="agent-bom read-only scanner"

# 2. Grant read-only roles at the project scope.
gcloud projects add-iam-policy-binding "$PROJECT_ID" \\
  --member="serviceAccount:$SA_EMAIL" \\
  --role="roles/viewer"
gcloud projects add-iam-policy-binding "$PROJECT_ID" \\
  --member="serviceAccount:$SA_EMAIL" \\
  --role="roles/iam.securityReviewer"

# 3. (Optional) Mint a key file for non-GCP runners. Prefer Workload Identity
#    Federation (keyless) in production. The key is written to your own disk.
#    gcloud iam service-accounts keys create agent-bom-key.json \\
#      --iam-account="$SA_EMAIL"

echo
echo "Service account created. Establish the read-only connection with:"
echo
echo "  agent-bom connect gcp \\"
echo "    --service-account $SA_EMAIL \\"
echo "    --project {proj} \\"
echo "    --key-file agent-bom-key.json"
"""


# ── Snowflake: read-only governance role ───────────────────────────────────────


def snowflake_sql(
    *,
    role: str = DEFAULT_SNOWFLAKE_ROLE,
    user: str = DEFAULT_SNOWFLAKE_USER,
    warehouse: str = DEFAULT_SNOWFLAKE_WAREHOUSE,
) -> str:
    """Return a SQL script that creates the read-only governance role.

    Grants ``IMPORTED PRIVILEGES`` on the ``SNOWFLAKE`` database (ACCOUNT_USAGE /
    INFORMATION_SCHEMA metadata views only — no customer warehouse rows) and
    warehouse ``USAGE``. No DML/DDL on customer data. Round-trips into
    ``connect snowflake --user <user> --role <role> --warehouse <warehouse>``.
    Run as ACCOUNTADMIN.
    """
    role = _validate_snowflake_identifier(role, field="role")
    user = _validate_snowflake_identifier(user, field="user")
    warehouse = _validate_snowflake_identifier(warehouse, field="warehouse")
    return f"""-- agent-bom Snowflake read-only onboarding.
-- Zero write access. Governance metadata only; customer data rows never read.
-- Run as ACCOUNTADMIN (agent-bom never executes this — your admin reviews + runs it).

-- 1. Read-only governance role.
CREATE ROLE IF NOT EXISTS {role}
  COMMENT = 'Read-only role for agent-bom governance scanning';

-- 2. Read access to Snowflake metadata views (ACCOUNT_USAGE / INFORMATION_SCHEMA).
--    No customer warehouse data is accessible via these views.
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE {role};

-- 3. Minimal scan warehouse (XS, auto-suspend 60s) + USAGE grant.
CREATE WAREHOUSE IF NOT EXISTS {warehouse}
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'agent-bom scan warehouse';
GRANT USAGE ON WAREHOUSE {warehouse} TO ROLE {role};

-- 4. Service user (key-pair auth only — no password) + role assignment.
CREATE USER IF NOT EXISTS {user}
  DEFAULT_ROLE = {role}
  DEFAULT_WAREHOUSE = {warehouse}
  COMMENT = 'agent-bom read-only scan service account — key-pair auth only';
GRANT ROLE {role} TO USER {user};

-- 5. Register your public key (generate locally; never share the private key):
--    openssl genrsa 2048 | openssl pkcs8 -topk8 -nocrypt -out agent_bom_key.p8
--    openssl rsa -in agent_bom_key.p8 -pubout -out agent_bom_key.pub
ALTER USER {user} SET RSA_PUBLIC_KEY='<PASTE_PUBLIC_KEY_CONTENT_HERE>';

-- Establish the read-only connection with:
--   agent-bom connect snowflake \\
--     --account <your-account-locator> \\
--     --user {user} \\
--     --role {role} \\
--     --warehouse {warehouse} \\
--     --private-key-file agent_bom_key.p8

-- Revoke instantly:
--   ALTER USER {user} SET DISABLED = TRUE;
"""


# ── registry / dispatch ────────────────────────────────────────────────────────

_DEFAULT_FORMATS: dict[str, str] = {
    "aws": "cloudformation",
    "azure": "bash",
    "gcp": "bash",
    "snowflake": "sql",
}


def default_emit_format(provider: str) -> str:
    """Return the natural artifact format for ``provider``."""
    try:
        return _DEFAULT_FORMATS[provider]
    except KeyError:
        raise ValueError(f"unknown provider: {provider!r}") from None


def emit_artifact(provider: str, fmt: str, *, options: Mapping[str, str]) -> str:
    """Dispatch to the right generator and return the artifact text.

    ``options`` carries provider-specific inputs (all optional):
      aws:       external_id, role_name, trusted_principal_arn
      azure:     subscription_id, app_name
      gcp:       project_id, service_account
      snowflake: role, user, warehouse
    """
    if provider not in _DEFAULT_FORMATS:
        raise ValueError(f"unknown provider: {provider!r}")
    if fmt != _DEFAULT_FORMATS[provider]:
        raise ValueError(f"unsupported format {fmt!r} for {provider!r}; expected {_DEFAULT_FORMATS[provider]!r}")
    opts = dict(options)
    if provider == "aws":
        return aws_cloudformation_template(
            external_id=opts.get("external_id") or generate_external_id(),
            role_name=opts.get("role_name") or DEFAULT_AWS_ROLE_NAME,
            trusted_principal_arn=opts.get("trusted_principal_arn", ""),
        )
    if provider == "azure":
        return azure_bootstrap_script(
            subscription_id=opts.get("subscription_id", ""),
            app_name=opts.get("app_name") or DEFAULT_AZURE_APP_NAME,
        )
    if provider == "gcp":
        return gcp_bootstrap_script(
            project_id=opts.get("project_id", ""),
            service_account=opts.get("service_account") or DEFAULT_GCP_SERVICE_ACCOUNT,
        )
    # snowflake
    return snowflake_sql(
        role=opts.get("role") or DEFAULT_SNOWFLAKE_ROLE,
        user=opts.get("user") or DEFAULT_SNOWFLAKE_USER,
        warehouse=opts.get("warehouse") or DEFAULT_SNOWFLAKE_WAREHOUSE,
    )


__all__ = [
    "generate_external_id",
    "aws_cloudformation_template",
    "azure_bootstrap_script",
    "gcp_bootstrap_script",
    "snowflake_sql",
    "default_emit_format",
    "emit_artifact",
]
