"""Packaged first-run sample projects."""

from __future__ import annotations

from pathlib import Path

FIRST_RUN_SAMPLE_FILES: dict[str, str] = {
    "README.md": """# First-Run AI Stack

Small sample project generated by `agent-bom samples first-run`.

Run:

```bash
agent-bom agents --inventory inventory.json -p . --enrich
```

The sample includes two agents, two MCP servers, placeholder credential
environment variable names, Python/npm manifests, and one prompt file. It does
not contain real credentials.
""",
    "inventory.json": """{
  "schema_version": "1",
  "source": "agent-bom-first-run-sample",
  "generated_at": "2026-04-25T00:00:00Z",
  "agents": [
    {
      "name": "Cursor First-Run Workspace",
      "agent_type": "cursor",
      "config_path": ".cursor/mcp.json",
      "source": "bundled-first-run-sample",
      "mcp_servers": [
        {
          "name": "research-filesystem",
          "command": "python",
          "args": ["services/research-mcp/server.py"],
          "transport": "stdio",
          "working_dir": "services/research-mcp",
          "config_path": ".cursor/mcp.json",
          "env": {
            "OPENAI_API_KEY": "${OPENAI_API_KEY}",
            "VECTOR_DB_TOKEN": "${VECTOR_DB_TOKEN}"
          },
          "tools": [
            {"name": "read_project_file", "description": "Read files inside the sample project workspace"},
            {"name": "summarize_research_notes", "description": "Summarize local notes for the agent"}
          ],
          "packages": [
            {"name": "flask", "version": "3.1.3", "ecosystem": "pypi"},
            {"name": "werkzeug", "version": "3.1.8", "ecosystem": "pypi"}
          ]
        },
        {
          "name": "browser-helper",
          "command": "node",
          "args": ["services/browser-helper/server.js"],
          "transport": "stdio",
          "working_dir": "services/browser-helper",
          "config_path": ".cursor/mcp.json",
          "env": {
            "BROWSER_SESSION_TOKEN": "${BROWSER_SESSION_TOKEN}"
          },
          "tools": [
            {"name": "fetch_page_title", "description": "Fetch a page title for demo automation"}
          ],
          "packages": [
            {"name": "axios", "version": "1.15.2", "ecosystem": "npm"},
            {"name": "lodash", "version": "4.18.0", "ecosystem": "npm"}
          ]
        }
      ]
    },
    {
      "name": "Claude Review Bot",
      "agent_type": "claude-code",
      "config_path": ".cursor/mcp.json",
      "source": "bundled-first-run-sample",
      "mcp_servers": [
        {
          "name": "research-filesystem",
          "command": "python",
          "args": ["services/research-mcp/server.py"],
          "transport": "stdio",
          "working_dir": "services/research-mcp",
          "config_path": ".cursor/mcp.json",
          "env": {
            "ANTHROPIC_API_KEY": "${ANTHROPIC_API_KEY}"
          },
          "tools": [
            {"name": "read_project_file", "description": "Read files inside the sample project workspace"}
          ],
          "packages": [
            {"name": "flask", "version": "3.1.3", "ecosystem": "pypi"}
          ]
        }
      ]
    }
  ]
}
""",
    ".cursor/mcp.json": """{
  "mcpServers": {
    "research-filesystem": {
      "command": "python",
      "args": ["services/research-mcp/server.py"],
      "env": {
        "OPENAI_API_KEY": "${OPENAI_API_KEY}",
        "VECTOR_DB_TOKEN": "${VECTOR_DB_TOKEN}"
      }
    },
    "browser-helper": {
      "command": "node",
      "args": ["services/browser-helper/server.js"],
      "env": {
        "BROWSER_SESSION_TOKEN": "${BROWSER_SESSION_TOKEN}"
      }
    }
  }
}
""",
    "services/research-mcp/requirements.txt": "flask==3.1.3\nwerkzeug==3.1.8\nrequests==2.33.1\n",
    "services/research-mcp/server.py": '''"""Tiny placeholder MCP-like server for first-run scanning."""

from pathlib import Path


def read_project_file(relative_path: str) -> str:
    base = Path(__file__).resolve().parents[2]
    target = (base / relative_path).resolve()
    if base not in target.parents and target != base:
        raise ValueError("path must stay inside the sample project")
    return target.read_text(encoding="utf-8")
''',
    "services/browser-helper/package.json": """{
  "name": "agent-bom-first-run-browser-helper",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "axios": "1.15.2",
    "lodash": "4.18.0"
  }
}
""",
    "services/browser-helper/package-lock.json": """{
  "name": "agent-bom-first-run-browser-helper",
  "version": "0.1.0",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "agent-bom-first-run-browser-helper",
      "version": "0.1.0",
      "dependencies": {
        "axios": "1.15.2",
        "lodash": "4.18.0"
      }
    },
    "node_modules/axios": {"version": "1.15.2"},
    "node_modules/lodash": {"version": "4.18.0"}
  }
}
""",
    "services/browser-helper/server.js": """const axios = require("axios");

async function fetchPageTitle(url) {
  const response = await axios.get(url, { timeout: 2000 });
  const match = String(response.data).match(/<title>(.*?)<\\/title>/i);
  return match ? match[1] : "untitled";
}

module.exports = { fetchPageTitle };
""",
    "prompts/agent-system-prompt.md": """# First-run support agent

You help a developer understand the local sample project. Stay inside the
workspace, cite the file you inspected, and do not request or print secret
values.
""",
}


def write_first_run_sample(destination: str | Path, *, force: bool = False) -> list[Path]:
    """Write the packaged first-run sample to ``destination``."""
    root = Path(destination)
    if root.exists() and any(root.iterdir()) and not force:
        raise FileExistsError(f"{root} already exists and is not empty; pass force=True to overwrite sample files")

    written: list[Path] = []
    for relative, content in FIRST_RUN_SAMPLE_FILES.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written
