#!/usr/bin/env bash
# Bootstrap a gated hosted demo (Phase 0) on a single VM.
#
# Targets demo.agent-bom.com by default: secrets, compose, optional seed,
# optional tester-key mint, and Caddy front-door instructions.
#
# Prereqs on the VM: Docker + Compose v2, DNS A record, inbound 443 (and SSH).
# Caddy is installed separately — see --print-caddy or docs/HOSTED_POC.md.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${AGENT_BOM_HOSTED_ENV_FILE:-$ROOT_DIR/.env.hosted-poc}"
COMPOSE_FILES=(
  -f "$ROOT_DIR/deploy/docker-compose.platform.yml"
  -f "$ROOT_DIR/deploy/docker-compose.hosted-poc.yml"
)

DOMAIN="${AGENT_BOM_HOSTED_DOMAIN:-demo.agent-bom.com}"
ACME_EMAIL="${ACME_EMAIL:-}"
PUBLIC_URL="https://${DOMAIN}"
STATE_DIR="${HOME}/.agent-bom/hosted-demo"
DRY_RUN=0
GENERATE_SECRETS=0
SKIP_PREFLIGHT=0
SKIP_UP=0
SEED=0
MINT_TESTER_KEY=0
TESTER_KEY_NAME="demo-tester"
TESTER_KEY_ROLE="viewer"
PRINT_CADDY=0
WAIT_HEALTH=0

usage() {
  cat <<'EOF'
Phase 0 hosted demo bootstrap (demo.agent-bom.com).

Generates secrets, runs hosted POC preflight, starts platform compose, optionally
seeds quickstart data, and can mint a read-only tester API key.

Usage:
  scripts/deploy/demo-hosted.sh [options]

Options:
  --domain HOST               Public hostname (default: demo.agent-bom.com)
  --acme-email EMAIL          Let's Encrypt contact (for Caddy env; optional here)
  --env-file PATH             Env file to load/write (default: .env.hosted-poc)
  --state-dir PATH            Operator notes directory (default: ~/.agent-bom/hosted-demo)
  --generate-secrets          Write a new env file with random secrets (fails if exists)
  --skip-preflight            Skip scripts/deploy/hosted_poc_preflight.py
  --skip-up                   Do not run docker compose up
  --seed                      Run agent-bom quickstart --run --offline --force in api
  --mint-tester-key           POST /v1/auth/keys (viewer) using bootstrap admin key
  --tester-name NAME          Tester key label (default: demo-tester)
  --tester-role ROLE          Tester key role (default: viewer)
  --wait-health               Poll http://127.0.0.1:8422/health after compose up
  --print-caddy               Print Caddy install + reload commands and exit
  --dry-run                   Print actions without applying changes
  -h, --help                  Show this help

Typical first run on a fresh VM (after DNS points at the host):

  git clone https://github.com/msaad00/agent-bom.git && cd agent-bom
  scripts/deploy/demo-hosted.sh --generate-secrets --domain demo.agent-bom.com --seed --mint-tester-key
  scripts/deploy/demo-hosted.sh --print-caddy

Then install Caddy using deploy/caddy/Caddyfile.hosted-poc and verify:

  scripts/deploy/verify-hosted-demo.sh --domain demo.agent-bom.com

See docs/HOSTED_POC.md and docs/ROADMAP_SAAS.md for the full road.
EOF
}

log() { printf "\n[%s] %s\n" "$(date +%H:%M:%S)" "$*"; }
warn() { printf "\n[warn] %s\n" "$*" >&2; }
die() { printf "\n[error] %s\n" "$*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '[dry-run]'; printf ' %q' "$@"; printf '\n'
    return 0
  fi
  "$@"
}

fernet_key() {
  if python3 - <<'PY' >/dev/null 2>&1
import cryptography.fernet  # noqa: F401
PY
  then
    python3 - <<'PY'
from cryptography.fernet import Fernet
print(Fernet.generate_key().decode())
PY
    return
  fi
  if command -v docker >/dev/null 2>&1; then
    docker run --rm python:3.11-slim python - <<'PY'
from cryptography.fernet import Fernet
print(Fernet.generate_key().decode())
PY
    return
  fi
  die "need python3+cryptography or docker to generate AGENT_BOM_CONNECTIONS_KEY"
}

write_env_file() {
  [[ -f "$ENV_FILE" ]] && die "env file already exists: $ENV_FILE (remove or pick --env-file)"
  need_cmd openssl
  local pg_pass app_pass api_key audit_key session_key connections_key
  pg_pass="$(openssl rand -hex 32)"
  app_pass="$(openssl rand -hex 32)"
  api_key="$(openssl rand -hex 32)"
  audit_key="$(openssl rand -hex 32)"
  session_key="$(openssl rand -hex 32)"
  connections_key="$(fernet_key)"

  run mkdir -p "$(dirname "$ENV_FILE")"
  run tee "$ENV_FILE" >/dev/null <<EOF
# Generated by scripts/deploy/demo-hosted.sh — do not commit.
POSTGRES_PASSWORD=$pg_pass
POSTGRES_APP_PASSWORD=$app_pass
AGENT_BOM_API_KEY=$api_key
AGENT_BOM_AUDIT_HMAC_KEY=$audit_key
AGENT_BOM_BROWSER_SESSION_SIGNING_KEY=$session_key
AGENT_BOM_CONNECTIONS_KEY=$connections_key
NEXT_PUBLIC_API_URL=$PUBLIC_URL
CORS_ORIGINS=$PUBLIC_URL,http://ui:3000
AGENT_BOM_SESSION_COOKIE_SECURE=1
AGENT_BOM_HOSTED_DOMAIN=$DOMAIN
ACME_EMAIL=$ACME_EMAIL
EOF
  run chmod 0600 "$ENV_FILE"
  log "wrote $ENV_FILE"
}

load_env() {
  [[ -f "$ENV_FILE" ]] || die "env file not found: $ENV_FILE (run with --generate-secrets first)"
  # shellcheck disable=SC1090
  set -a
  source "$ENV_FILE"
  set +a
  export NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL:-$PUBLIC_URL}"
  export CORS_ORIGINS="${CORS_ORIGINS:-$PUBLIC_URL,http://ui:3000}"
  export AGENT_BOM_SESSION_COOKIE_SECURE="${AGENT_BOM_SESSION_COOKIE_SECURE:-1}"
}

compose() {
  run docker compose "${COMPOSE_FILES[@]}" "$@"
}

preflight() {
  log "running hosted POC preflight"
  run python3 "$ROOT_DIR/scripts/deploy/hosted_poc_preflight.py" --write-postgres-secret
}

wait_for_health() {
  local attempts=60
  log "waiting for API health on 127.0.0.1:8422"
  for ((i = 1; i <= attempts; i++)); do
    if curl -fsS "http://127.0.0.1:8422/health" >/dev/null 2>&1; then
      log "API healthy"
      return 0
    fi
    sleep 2
  done
  die "API did not become healthy within $((attempts * 2))s"
}

seed_demo() {
  log "seeding quickstart demo graph"
  compose exec -T api agent-bom quickstart --run --offline --force
}

mint_tester_key() {
  need_cmd curl
  need_cmd python3
  local admin_key="${AGENT_BOM_API_KEY:-}"
  [[ -n "$admin_key" ]] || die "AGENT_BOM_API_KEY missing from env file"
  log "minting tester API key ($TESTER_KEY_NAME, role=$TESTER_KEY_ROLE)"
  local payload response tester_key
  payload="$(python3 - <<PY
import json
print(json.dumps({"name": "$TESTER_KEY_NAME", "role": "$TESTER_KEY_ROLE"}))
PY
)"
  response="$(curl -fsS -X POST "http://127.0.0.1:8422/v1/auth/keys" \
    -H "Authorization: Bearer $admin_key" \
    -H "Content-Type: application/json" \
    -d "$payload")"
  tester_key="$(printf '%s' "$response" | python3 - <<'PY'
import json, sys
data = json.loads(sys.stdin.read())
print(data.get("raw_key") or data.get("key") or data.get("api_key") or "")
PY
)"
  [[ -n "$tester_key" ]] || die "tester key mint failed: $response"
  run mkdir -p "$STATE_DIR"
  local note="$STATE_DIR/tester-key-${TESTER_KEY_NAME}.txt"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "would write tester key to $note"
    return 0
  fi
  umask 077
  printf '%s\n' "$tester_key" >"$note"
  log "tester key written to $note (share once; paste in UI auth gate)"
}

print_operator_summary() {
  run mkdir -p "$STATE_DIR"
  local summary="$STATE_DIR/operator-summary.txt"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "would write operator summary to $summary"
    return 0
  fi
  cat >"$summary" <<EOF
agent-bom hosted demo operator summary
======================================
Domain:        $DOMAIN
Public URL:    $PUBLIC_URL
Env file:      $ENV_FILE
Compose:       docker compose -f deploy/docker-compose.platform.yml -f deploy/docker-compose.hosted-poc.yml

Bootstrap admin API key: see AGENT_BOM_API_KEY in $ENV_FILE
Tester key (if minted):  $STATE_DIR/tester-key-${TESTER_KEY_NAME}.txt

Verify:
  scripts/deploy/verify-hosted-demo.sh --domain $DOMAIN

Caddy:
  scripts/deploy/demo-hosted.sh --print-caddy --domain $DOMAIN
EOF
  log "operator summary: $summary"
}

print_caddy_instructions() {
  cat <<EOF

Caddy front door (run on the VM as root or via sudo)
----------------------------------------------------
1. Install Caddy: https://caddyserver.com/docs/install#debian-ubuntu-raspbian
2. Copy the hosted POC Caddyfile:

   sudo mkdir -p /etc/caddy
   sudo cp $ROOT_DIR/deploy/caddy/Caddyfile.hosted-poc /etc/caddy/Caddyfile

3. Set environment for the Caddy service (systemd drop-in or /etc/default/caddy):

   ACME_EMAIL=${ACME_EMAIL:-you@example.com}
   AGENT_BOM_HOSTED_DOMAIN=$DOMAIN

4. Reload and enable:

   sudo systemctl enable --now caddy
   sudo systemctl reload caddy

5. Confirm only 443 is public; API/UI stay on 127.0.0.1:8422 and :3000.

EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain) DOMAIN="$2"; PUBLIC_URL="https://${DOMAIN}"; shift 2 ;;
    --acme-email) ACME_EMAIL="$2"; shift 2 ;;
    --env-file) ENV_FILE="$2"; shift 2 ;;
    --state-dir) STATE_DIR="$2"; shift 2 ;;
    --generate-secrets) GENERATE_SECRETS=1; shift ;;
    --skip-preflight) SKIP_PREFLIGHT=1; shift ;;
    --skip-up) SKIP_UP=1; shift ;;
    --seed) SEED=1; shift ;;
    --mint-tester-key) MINT_TESTER_KEY=1; shift ;;
    --tester-name) TESTER_KEY_NAME="$2"; shift 2 ;;
    --tester-role) TESTER_KEY_ROLE="$2"; shift 2 ;;
    --wait-health) WAIT_HEALTH=1; shift ;;
    --print-caddy) PRINT_CADDY=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
done

if [[ "$PRINT_CADDY" -eq 1 ]]; then
  print_caddy_instructions
  exit 0
fi

cd "$ROOT_DIR"

if [[ "$GENERATE_SECRETS" -eq 1 ]]; then
  write_env_file
fi

load_env

if [[ "$SKIP_PREFLIGHT" -eq 0 ]]; then
  preflight
fi

if [[ "$SKIP_UP" -eq 0 ]]; then
  log "starting platform compose"
  compose up -d --build
  if [[ "$WAIT_HEALTH" -eq 1 || "$SEED" -eq 1 || "$MINT_TESTER_KEY" -eq 1 ]]; then
    wait_for_health
  fi
fi

if [[ "$SEED" -eq 1 ]]; then
  seed_demo
fi

if [[ "$MINT_TESTER_KEY" -eq 1 ]]; then
  mint_tester_key
fi

print_operator_summary
log "done — install Caddy next: scripts/deploy/demo-hosted.sh --print-caddy --domain $DOMAIN"
