#!/usr/bin/env python3
"""Preflight a gated hosted POC compose deployment.

This is intentionally stdlib-only so it can run on a fresh VM before the
Python project dependencies are installed.

Control-plane and Postgres secrets must live as files under deploy/secrets/
— never as values in process env or .env.
"""

from __future__ import annotations

import argparse
import base64
import os
import secrets
import stat
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlparse

# Non-secret env still required for hosted URL wiring.
REQUIRED_ENV = (
    "NEXT_PUBLIC_API_URL",
    "CORS_ORIGINS",
)

# Env var names that must NEVER hold secret material for hosted/compose.
FORBIDDEN_SECRET_ENV = (
    "POSTGRES_PASSWORD",
    "POSTGRES_APP_PASSWORD",
    "AGENT_BOM_API_KEY",
    "AGENT_BOM_API_KEYS",
    "AGENT_BOM_AUDIT_HMAC_KEY",
    "AGENT_BOM_BROWSER_SESSION_SIGNING_KEY",
    "AGENT_BOM_CONNECTIONS_KEY",
    "AGENT_BOM_TRUST_PROXY_AUTH_SECRET",
    "AGENT_BOM_RATE_LIMIT_KEY",
    "AGENT_BOM_SCIM_BEARER_TOKEN",
)

# Required secret files (basename under deploy/secrets/).
REQUIRED_SECRET_FILES = (
    "postgres_password",
    "postgres_app_password",
    "api_key",
    "audit_hmac_key",
    "browser_session_signing_key",
    "connections_key",
)

# Optional secret files written by --write-secret for completeness.
OPTIONAL_SECRET_FILES = (
    "rate_limit_key",
    "trust_proxy_auth_secret",
    "scim_bearer_token",
)

SECRET_MIN_LENGTH = 32
LOCAL_HOSTS = {"localhost", "127.0.0.1", "0.0.0.0", "::1"}
TRUTHY = {"1", "true", "yes", "on"}


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _fail(errors: list[str], message: str) -> None:
    errors.append(message)


def _secrets_dir(root: Path) -> Path:
    return root / "deploy" / "secrets"


def _read_secret_file(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip("\r\n")


def _validate_no_secret_env(errors: list[str]) -> None:
    for name in FORBIDDEN_SECRET_ENV:
        if os.environ.get(name, "").strip():
            _fail(
                errors,
                f"{name} must not be set — write deploy/secrets/ files instead "
                "(never store control-plane or Postgres secrets in env / .env)",
            )


def _validate_required_env(errors: list[str]) -> None:
    for name in REQUIRED_ENV:
        if not os.environ.get(name, "").strip():
            _fail(errors, f"{name} is required")


def _validate_secret_files(root: Path, errors: list[str]) -> None:
    values: dict[str, str] = {}
    for name in REQUIRED_SECRET_FILES:
        path = _secrets_dir(root) / name
        if not path.is_file():
            _fail(errors, f"missing secret file: {path}")
            continue
        value = _read_secret_file(path)
        if len(value) < SECRET_MIN_LENGTH:
            _fail(errors, f"{path.name} must be at least {SECRET_MIN_LENGTH} characters")
        if "replace_me" in value.lower() or "change-me" in value.lower() or "example" in value.lower():
            _fail(errors, f"{path.name} still looks like a placeholder")
        previous = next((other for other, other_value in values.items() if other_value == value), None)
        if previous:
            _fail(errors, f"{path.name} must not reuse the same secret value as {previous}")
        values[path.name] = value

    connections = values.get("connections_key")
    if connections:
        try:
            decoded = base64.urlsafe_b64decode(connections.encode("ascii"))
        except Exception:
            _fail(
                errors,
                "connections_key must be a Fernet key generated by cryptography.fernet.Fernet.generate_key()",
            )
            return
        if len(decoded) != 32:
            _fail(errors, "connections_key must decode to 32 bytes")


def _validate_public_url(errors: list[str]) -> str:
    raw = os.environ.get("NEXT_PUBLIC_API_URL", "")
    parsed = urlparse(raw)
    if parsed.scheme != "https":
        _fail(errors, "NEXT_PUBLIC_API_URL must be an https:// URL for hosted POC")
    if not parsed.netloc:
        _fail(errors, "NEXT_PUBLIC_API_URL must include a host")
    host = (parsed.hostname or "").lower()
    if host in LOCAL_HOSTS or host.endswith(".local"):
        _fail(errors, "NEXT_PUBLIC_API_URL must not point at localhost or a local-only host")
    return raw.rstrip("/")


def _validate_cors(errors: list[str], public_url: str) -> None:
    raw = os.environ.get("CORS_ORIGINS", "")
    origins = {origin.strip().rstrip("/") for origin in raw.split(",") if origin.strip()}
    if "*" in origins:
        _fail(errors, "CORS_ORIGINS must not contain '*' for hosted POC")
    if public_url and public_url not in origins:
        _fail(errors, "CORS_ORIGINS must include NEXT_PUBLIC_API_URL")
    for origin in origins:
        parsed = urlparse(origin)
        host = (parsed.hostname or "").lower()
        if parsed.scheme == "http" and origin != "http://ui:3000":
            _fail(errors, "CORS_ORIGINS contains a non-internal http origin")
        if host in {"0.0.0.0", "127.0.0.1", "localhost"}:
            _fail(errors, "CORS_ORIGINS contains a local host origin")


def _validate_auth_and_bindings(errors: list[str]) -> None:
    unauth = os.environ.get("AGENT_BOM_ALLOW_UNAUTHENTICATED_API", "")
    if unauth.strip().lower() in TRUTHY:
        _fail(errors, "AGENT_BOM_ALLOW_UNAUTHENTICATED_API must be unset or false")

    for name in ("AGENT_BOM_API_BIND_HOST", "AGENT_BOM_UI_BIND_HOST"):
        value = os.environ.get(name, "127.0.0.1")
        if value not in {"127.0.0.1", "localhost", "::1"}:
            _fail(errors, f"{name} must stay loopback-only")

    if os.environ.get("AGENT_BOM_SESSION_COOKIE_SECURE", "1").strip().lower() in {"0", "false", "no", "off"}:
        _fail(errors, "AGENT_BOM_SESSION_COOKIE_SECURE must stay enabled")

    ephemeral_audit = os.environ.get("AGENT_BOM_ALLOW_EPHEMERAL_AUDIT_HMAC", "")
    if ephemeral_audit.strip().lower() in TRUTHY:
        _fail(errors, "AGENT_BOM_ALLOW_EPHEMERAL_AUDIT_HMAC must be unset or false")


def _fernet_key() -> str:
    # 32 random bytes → urlsafe base64 Fernet key (no cryptography dependency).
    return base64.urlsafe_b64encode(secrets.token_bytes(32)).decode("ascii")


def _write_secret_files(root: Path, *, force: bool) -> None:
    secrets_dir = _secrets_dir(root)
    secrets_dir.mkdir(parents=True, exist_ok=True)
    writers = {
        "postgres_password": lambda: secrets.token_hex(32),
        "postgres_app_password": lambda: secrets.token_hex(32),
        "api_key": lambda: secrets.token_hex(32),
        "audit_hmac_key": lambda: secrets.token_hex(32),
        "browser_session_signing_key": lambda: secrets.token_hex(32),
        "connections_key": _fernet_key,
        "rate_limit_key": lambda: secrets.token_hex(32),
        "trust_proxy_auth_secret": lambda: secrets.token_hex(32),
        "scim_bearer_token": lambda: secrets.token_hex(32),
    }
    for name in (*REQUIRED_SECRET_FILES, *OPTIONAL_SECRET_FILES):
        secret_path = secrets_dir / name
        if secret_path.exists() and not force:
            print(f"secret already exists: {secret_path}")
            continue
        secret_path.write_text(writers[name](), encoding="utf-8")
        secret_path.chmod(stat.S_IRUSR)
        print(f"wrote {secret_path} with mode 0400")


def _compose_config(root: Path) -> str:
    command = [
        "docker",
        "compose",
        "-f",
        str(root / "deploy" / "docker-compose.platform.yml"),
        "-f",
        str(root / "deploy" / "docker-compose.hosted-poc.yml"),
        "config",
    ]
    result = subprocess.run(command, cwd=root, check=False, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "docker compose config failed")
    return result.stdout


def _validate_compose_config(errors: list[str], rendered: str) -> None:
    forbidden = {
        "0.0.0.0:3000": "UI must not bind publicly",
        "0.0.0.0:8422": "API must not bind publicly",
        "postgres_password.example": "platform compose must not mount the placeholder Postgres password",
        "postgres_app_password.example": "platform compose must not mount the placeholder app password",
        "--allow-insecure-no-auth": "hosted compose must not allow unauthenticated API mode",
        "AGENT_BOM_ALLOW_UNAUTHENTICATED_API": "hosted compose must not opt into unauthenticated API",
        "NEXT_PUBLIC_API_URL: http://localhost": "UI must not bake localhost API URL",
        "POSTGRES_PASSWORD:": "compose must not interpolate POSTGRES_PASSWORD from env",
        "POSTGRES_APP_PASSWORD:": "compose must not interpolate POSTGRES_APP_PASSWORD from env",
    }
    for needle, message in forbidden.items():
        if needle in rendered:
            _fail(errors, message)

    for env_name in (
        "AGENT_BOM_API_KEY",
        "AGENT_BOM_AUDIT_HMAC_KEY",
        "AGENT_BOM_CONNECTIONS_KEY",
        "AGENT_BOM_BROWSER_SESSION_SIGNING_KEY",
    ):
        for line in rendered.splitlines():
            stripped = line.strip().lstrip("- ").strip()
            if stripped.startswith(f"{env_name}_FILE"):
                continue
            if stripped.startswith(f"{env_name}:") or stripped.startswith(f"{env_name}="):
                if "${" in stripped:
                    _fail(errors, f"compose must not interpolate {env_name} from env")

    if "AGENT_BOM_SESSION_COOKIE_SECURE=1" not in rendered and 'AGENT_BOM_SESSION_COOKIE_SECURE: "1"' not in rendered:
        _fail(errors, "compose output must set AGENT_BOM_SESSION_COOKIE_SECURE=1")
    if "AGENT_BOM_POSTGRES_PASSWORD_FILE" not in rendered:
        _fail(errors, "compose output must mount AGENT_BOM_POSTGRES_PASSWORD_FILE for agent_bom_app")
    for file_env in (
        "AGENT_BOM_API_KEY_FILE",
        "AGENT_BOM_AUDIT_HMAC_KEY_FILE",
        "AGENT_BOM_BROWSER_SESSION_SIGNING_KEY_FILE",
        "AGENT_BOM_CONNECTIONS_KEY_FILE",
    ):
        if file_env not in rendered:
            _fail(errors, f"compose output must set {file_env}")
    if "postgresql://agent_bom_app@" not in rendered and "postgresql://agent_bom_app%40" not in rendered:
        if "agent_bom_app@" not in rendered:
            _fail(errors, "compose output must connect as agent_bom_app (never bootstrap/admin)")


def run_preflight(root: Path, *, skip_compose: bool, write_secret: bool, force: bool) -> list[str]:
    errors: list[str] = []
    _validate_no_secret_env(errors)
    _validate_required_env(errors)
    public_url = _validate_public_url(errors)
    _validate_cors(errors, public_url)
    _validate_auth_and_bindings(errors)

    if write_secret and not errors:
        _write_secret_files(root, force=force)

    _validate_secret_files(root, errors)

    if not skip_compose:
        try:
            rendered = _compose_config(root)
        except Exception:
            _fail(errors, "docker compose config failed")
        else:
            _validate_compose_config(errors, rendered)

    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=_repo_root())
    parser.add_argument("--skip-compose", action="store_true")
    parser.add_argument("--write-secret", action="store_true")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args(argv)

    errors = run_preflight(
        args.root,
        skip_compose=args.skip_compose,
        write_secret=args.write_secret,
        force=args.force,
    )
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1
    print("hosted POC preflight OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
