#!/usr/bin/env python3
"""Preflight a gated hosted POC compose deployment.

This is intentionally stdlib-only so it can run on a fresh VM before the
Python project dependencies are installed.
"""

from __future__ import annotations

import argparse
import base64
import os
import secrets
import stat
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlparse

REQUIRED_ENV = (
    "AGENT_BOM_API_KEY",
    "AGENT_BOM_AUDIT_HMAC_KEY",
    "AGENT_BOM_BROWSER_SESSION_SIGNING_KEY",
    "AGENT_BOM_CONNECTIONS_KEY",
    "NEXT_PUBLIC_API_URL",
    "CORS_ORIGINS",
)

SECRET_MIN_LENGTH = 32
LOCAL_HOSTS = {"localhost", "127.0.0.1", "0.0.0.0", "::1"}
TRUTHY = {"1", "true", "yes", "on"}
UNIQUE_SECRET_ENV = (
    "AGENT_BOM_API_KEY",
    "AGENT_BOM_AUDIT_HMAC_KEY",
    "AGENT_BOM_BROWSER_SESSION_SIGNING_KEY",
    "AGENT_BOM_CONNECTIONS_KEY",
)
POSTGRES_SECRET_NAMES = (
    "postgres_password",
    "postgres_app_password",
)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _fail(errors: list[str], message: str) -> None:
    errors.append(message)


def _validate_secret_lengths(errors: list[str]) -> None:
    for name in REQUIRED_ENV:
        value = os.environ.get(name, "")
        if not value:
            _fail(errors, f"{name} is required")
            continue
        if name.endswith("_KEY"):
            if len(value) < SECRET_MIN_LENGTH:
                _fail(errors, f"{name} must be at least {SECRET_MIN_LENGTH} characters")
            if "change-me" in value.lower() or "replace" in value.lower():
                _fail(errors, f"{name} still looks like a placeholder")


def _validate_fernet_key(errors: list[str]) -> None:
    value = os.environ.get("AGENT_BOM_CONNECTIONS_KEY", "")
    if not value:
        return
    try:
        decoded = base64.urlsafe_b64decode(value.encode("ascii"))
    except Exception:
        _fail(errors, "AGENT_BOM_CONNECTIONS_KEY must be a Fernet key generated by cryptography.fernet.Fernet.generate_key()")
        return
    if len(decoded) != 32:
        _fail(errors, "AGENT_BOM_CONNECTIONS_KEY must decode to 32 bytes")


def _validate_secret_uniqueness(errors: list[str]) -> None:
    seen: dict[str, str] = {}
    for name in UNIQUE_SECRET_ENV:
        value = os.environ.get(name, "")
        if not value:
            continue
        previous = seen.get(value)
        if previous:
            _fail(errors, f"{name} must not reuse the same secret value as {previous}")
            continue
        seen[value] = name


def _validate_no_postgres_password_env(errors: list[str]) -> None:
    for name in ("POSTGRES_PASSWORD", "POSTGRES_APP_PASSWORD"):
        if os.environ.get(name, "").strip():
            _fail(
                errors,
                f"{name} must not be set — write deploy/secrets/postgres_* files instead "
                "(never store Postgres passwords in env / .env)",
            )


def _secrets_dir(root: Path) -> Path:
    return root / "deploy" / "secrets"


def _validate_postgres_secret_files(root: Path, errors: list[str]) -> None:
    values: dict[str, str] = {}
    for name in POSTGRES_SECRET_NAMES:
        path = _secrets_dir(root) / name
        if not path.is_file():
            _fail(errors, f"missing Postgres secret file: {path}")
            continue
        value = path.read_text(encoding="utf-8").strip()
        if len(value) < SECRET_MIN_LENGTH:
            _fail(errors, f"{path.name} must be at least {SECRET_MIN_LENGTH} characters")
        if "replace_me" in value.lower() or "change-me" in value.lower() or "example" in value.lower():
            _fail(errors, f"{path.name} still looks like a placeholder")
        previous = next((other for other, other_value in values.items() if other_value == value), None)
        if previous:
            _fail(errors, f"{path.name} must not reuse the same secret value as {previous}")
        values[path.name] = value


def _validate_public_url(errors: list[str]) -> str:
    raw = os.environ.get("NEXT_PUBLIC_API_URL", "")
    parsed = urlparse(raw)
    if parsed.scheme != "https":
        _fail(errors, "NEXT_PUBLIC_API_URL must be an https:// URL for hosted POC")
    if not parsed.netloc:
        _fail(errors, "NEXT_PUBLIC_API_URL must include a host")
    host = (parsed.hostname or "").lower()
    if host in LOCAL_HOSTS or host.endswith(".local"):
        _fail(errors, "NEXT_PUBLIC_API_URL must not point at localhost or a local-only host")
    return raw.rstrip("/")


def _validate_cors(errors: list[str], public_url: str) -> None:
    raw = os.environ.get("CORS_ORIGINS", "")
    origins = {origin.strip().rstrip("/") for origin in raw.split(",") if origin.strip()}
    if "*" in origins:
        _fail(errors, "CORS_ORIGINS must not contain '*' for hosted POC")
    if public_url and public_url not in origins:
        _fail(errors, "CORS_ORIGINS must include NEXT_PUBLIC_API_URL")
    for origin in origins:
        parsed = urlparse(origin)
        host = (parsed.hostname or "").lower()
        if parsed.scheme == "http" and origin != "http://ui:3000":
            _fail(errors, "CORS_ORIGINS contains a non-internal http origin")
        if host in {"0.0.0.0", "127.0.0.1", "localhost"}:
            _fail(errors, "CORS_ORIGINS contains a local host origin")


def _validate_auth_and_bindings(errors: list[str]) -> None:
    unauth = os.environ.get("AGENT_BOM_ALLOW_UNAUTHENTICATED_API", "")
    if unauth.strip().lower() in TRUTHY:
        _fail(errors, "AGENT_BOM_ALLOW_UNAUTHENTICATED_API must be unset or false")

    for name in ("AGENT_BOM_API_BIND_HOST", "AGENT_BOM_UI_BIND_HOST"):
        value = os.environ.get(name, "127.0.0.1")
        if value not in {"127.0.0.1", "localhost", "::1"}:
            _fail(errors, f"{name} must stay loopback-only")

    if os.environ.get("AGENT_BOM_SESSION_COOKIE_SECURE", "1").strip().lower() in {"0", "false", "no", "off"}:
        _fail(errors, "AGENT_BOM_SESSION_COOKIE_SECURE must stay enabled")

    ephemeral_audit = os.environ.get("AGENT_BOM_ALLOW_EPHEMERAL_AUDIT_HMAC", "")
    if ephemeral_audit.strip().lower() in TRUTHY:
        _fail(errors, "AGENT_BOM_ALLOW_EPHEMERAL_AUDIT_HMAC must be unset or false")


def _write_postgres_secrets(root: Path, *, force: bool) -> None:
    secrets_dir = _secrets_dir(root)
    secrets_dir.mkdir(parents=True, exist_ok=True)
    for name in POSTGRES_SECRET_NAMES:
        secret_path = secrets_dir / name
        if secret_path.exists() and not force:
            print(f"postgres secret already exists: {secret_path}")
            continue
        secret_path.write_text(secrets.token_hex(32), encoding="utf-8")
        secret_path.chmod(stat.S_IRUSR)
        print(f"wrote {secret_path} with mode 0400")


def _compose_config(root: Path) -> str:
    command = [
        "docker",
        "compose",
        "-f",
        str(root / "deploy" / "docker-compose.platform.yml"),
        "-f",
        str(root / "deploy" / "docker-compose.hosted-poc.yml"),
        "config",
    ]
    result = subprocess.run(command, cwd=root, check=False, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "docker compose config failed")
    return result.stdout


def _validate_compose_config(errors: list[str], rendered: str) -> None:
    forbidden = {
        "0.0.0.0:3000": "UI must not bind publicly",
        "0.0.0.0:8422": "API must not bind publicly",
        "postgres_password.example": "platform compose must not mount the placeholder Postgres password",
        "postgres_app_password.example": "platform compose must not mount the placeholder app password",
        "--allow-insecure-no-auth": "hosted compose must not allow unauthenticated API mode",
        "AGENT_BOM_ALLOW_UNAUTHENTICATED_API": "hosted compose must not opt into unauthenticated API",
        "NEXT_PUBLIC_API_URL: http://localhost": "UI must not bake localhost API URL",
        "POSTGRES_PASSWORD:": "compose must not interpolate POSTGRES_PASSWORD from env",
        "POSTGRES_APP_PASSWORD:": "compose must not interpolate POSTGRES_APP_PASSWORD from env",
    }
    for needle, message in forbidden.items():
        if needle in rendered:
            _fail(errors, message)
    if "AGENT_BOM_SESSION_COOKIE_SECURE=1" not in rendered and 'AGENT_BOM_SESSION_COOKIE_SECURE: "1"' not in rendered:
        _fail(errors, "compose output must set AGENT_BOM_SESSION_COOKIE_SECURE=1")
    if "AGENT_BOM_POSTGRES_PASSWORD_FILE" not in rendered:
        _fail(errors, "compose output must mount AGENT_BOM_POSTGRES_PASSWORD_FILE for agent_bom_app")
    if "postgresql://agent_bom_app@" not in rendered and "postgresql://agent_bom_app%40" not in rendered:
        # url may stay unescaped
        if "agent_bom_app@" not in rendered:
            _fail(errors, "compose output must connect as agent_bom_app (never bootstrap/admin)")


def run_preflight(root: Path, *, skip_compose: bool, write_secret: bool, force: bool) -> list[str]:
    errors: list[str] = []
    _validate_no_postgres_password_env(errors)
    _validate_secret_lengths(errors)
    _validate_fernet_key(errors)
    _validate_secret_uniqueness(errors)
    public_url = _validate_public_url(errors)
    _validate_cors(errors, public_url)
    _validate_auth_and_bindings(errors)

    if write_secret and not errors:
        _write_postgres_secrets(root, force=force)

    _validate_postgres_secret_files(root, errors)

    if not skip_compose:
        try:
            rendered = _compose_config(root)
        except Exception:
            _fail(errors, "docker compose config failed")
        else:
            _validate_compose_config(errors, rendered)

    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=_repo_root())
    parser.add_argument("--skip-compose", action="store_true")
    parser.add_argument("--write-secret", action="store_true")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args(argv)

    errors = run_preflight(
        args.root,
        skip_compose=args.skip_compose,
        write_secret=args.write_secret,
        force=args.force,
    )
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1
    print("hosted POC preflight OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
