#!/usr/bin/env python3
"""Preflight a gated hosted POC compose deployment.

This is intentionally stdlib-only so it can run on a fresh VM before the
Python project dependencies are installed.
"""

from __future__ import annotations

import argparse
import base64
import os
import stat
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlparse

REQUIRED_ENV = (
    "POSTGRES_PASSWORD",
    "POSTGRES_APP_PASSWORD",
    "AGENT_BOM_API_KEY",
    "AGENT_BOM_AUDIT_HMAC_KEY",
    "AGENT_BOM_BROWSER_SESSION_SIGNING_KEY",
    "AGENT_BOM_CONNECTIONS_KEY",
    "NEXT_PUBLIC_API_URL",
    "CORS_ORIGINS",
)

SECRET_MIN_LENGTH = 32
LOCAL_HOSTS = {"localhost", "127.0.0.1", "0.0.0.0", "::1"}
TRUTHY = {"1", "true", "yes", "on"}


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _fail(errors: list[str], message: str) -> None:
    errors.append(message)


def _validate_secret_lengths(errors: list[str]) -> None:
    for name in REQUIRED_ENV:
        value = os.environ.get(name, "")
        if not value:
            _fail(errors, f"{name} is required")
            continue
        if name.endswith("_KEY") or name.startswith("POSTGRES_"):
            if len(value) < SECRET_MIN_LENGTH:
                _fail(errors, f"{name} must be at least {SECRET_MIN_LENGTH} characters")
            if "change-me" in value.lower() or "replace" in value.lower():
                _fail(errors, f"{name} still looks like a placeholder")


def _validate_fernet_key(errors: list[str]) -> None:
    value = os.environ.get("AGENT_BOM_CONNECTIONS_KEY", "")
    if not value:
        return
    try:
        decoded = base64.urlsafe_b64decode(value.encode("ascii"))
    except Exception:
        _fail(errors, "AGENT_BOM_CONNECTIONS_KEY must be a Fernet key generated by cryptography.fernet.Fernet.generate_key()")
        return
    if len(decoded) != 32:
        _fail(errors, "AGENT_BOM_CONNECTIONS_KEY must decode to 32 bytes")


def _validate_public_url(errors: list[str]) -> str:
    raw = os.environ.get("NEXT_PUBLIC_API_URL", "")
    parsed = urlparse(raw)
    if parsed.scheme != "https":
        _fail(errors, "NEXT_PUBLIC_API_URL must be an https:// URL for hosted POC")
    if not parsed.netloc:
        _fail(errors, "NEXT_PUBLIC_API_URL must include a host")
    host = (parsed.hostname or "").lower()
    if host in LOCAL_HOSTS or host.endswith(".local"):
        _fail(errors, "NEXT_PUBLIC_API_URL must not point at localhost or a local-only host")
    return raw.rstrip("/")


def _validate_cors(errors: list[str], public_url: str) -> None:
    raw = os.environ.get("CORS_ORIGINS", "")
    origins = {origin.strip().rstrip("/") for origin in raw.split(",") if origin.strip()}
    if "*" in origins:
        _fail(errors, "CORS_ORIGINS must not contain '*' for hosted POC")
    if public_url and public_url not in origins:
        _fail(errors, "CORS_ORIGINS must include NEXT_PUBLIC_API_URL")
    for origin in origins:
        parsed = urlparse(origin)
        host = (parsed.hostname or "").lower()
        if parsed.scheme == "http" and origin != "http://ui:3000":
            _fail(errors, "CORS_ORIGINS contains a non-internal http origin")
        if host in {"0.0.0.0", "127.0.0.1", "localhost"}:
            _fail(errors, "CORS_ORIGINS contains a local host origin")


def _validate_auth_and_bindings(errors: list[str]) -> None:
    unauth = os.environ.get("AGENT_BOM_ALLOW_UNAUTHENTICATED_API", "")
    if unauth.strip().lower() in TRUTHY:
        _fail(errors, "AGENT_BOM_ALLOW_UNAUTHENTICATED_API must be unset or false")

    for name in ("AGENT_BOM_API_BIND_HOST", "AGENT_BOM_UI_BIND_HOST"):
        value = os.environ.get(name, "127.0.0.1")
        if value not in {"127.0.0.1", "localhost", "::1"}:
            _fail(errors, f"{name} must stay loopback-only")

    if os.environ.get("AGENT_BOM_SESSION_COOKIE_SECURE", "1").strip().lower() in {"0", "false", "no", "off"}:
        _fail(errors, "AGENT_BOM_SESSION_COOKIE_SECURE must stay enabled")


def _write_postgres_secret(root: Path, *, force: bool) -> None:
    secret_path = root / "deploy" / "secrets" / "postgres_password"
    secret_path.parent.mkdir(parents=True, exist_ok=True)
    if secret_path.exists() and not force:
        print(f"postgres secret already exists: {secret_path}")
        return
    secret_path.write_text(os.environ["POSTGRES_PASSWORD"], encoding="utf-8")
    secret_path.chmod(stat.S_IRUSR)
    print(f"wrote {secret_path} with mode 0400")


def _compose_config(root: Path) -> str:
    command = [
        "docker",
        "compose",
        "-f",
        str(root / "deploy" / "docker-compose.platform.yml"),
        "-f",
        str(root / "deploy" / "docker-compose.hosted-poc.yml"),
        "config",
    ]
    result = subprocess.run(command, cwd=root, check=False, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "docker compose config failed")
    return result.stdout


def _validate_compose_config(errors: list[str], rendered: str) -> None:
    forbidden = {
        "0.0.0.0:3000": "UI must not bind publicly",
        "0.0.0.0:8422": "API must not bind publicly",
        "postgres_password.example": "platform compose must not mount the placeholder Postgres password",
        "--allow-insecure-no-auth": "hosted compose must not allow unauthenticated API mode",
        "AGENT_BOM_ALLOW_UNAUTHENTICATED_API": "hosted compose must not opt into unauthenticated API",
        "NEXT_PUBLIC_API_URL: http://localhost": "UI must not bake localhost API URL",
    }
    for needle, message in forbidden.items():
        if needle in rendered:
            _fail(errors, message)
    if "AGENT_BOM_SESSION_COOKIE_SECURE=1" not in rendered and "AGENT_BOM_SESSION_COOKIE_SECURE: \"1\"" not in rendered:
        _fail(errors, "compose output must set AGENT_BOM_SESSION_COOKIE_SECURE=1")


def run_preflight(root: Path, *, skip_compose: bool, write_secret: bool, force: bool) -> list[str]:
    errors: list[str] = []
    _validate_secret_lengths(errors)
    _validate_fernet_key(errors)
    public_url = _validate_public_url(errors)
    _validate_cors(errors, public_url)
    _validate_auth_and_bindings(errors)

    if write_secret and not errors:
        _write_postgres_secret(root, force=force)

    if not skip_compose:
        try:
            rendered = _compose_config(root)
        except Exception:
            _fail(errors, "docker compose config failed")
        else:
            _validate_compose_config(errors, rendered)

    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Preflight a hosted agent-bom POC compose deployment")
    parser.add_argument("--root", type=Path, default=_repo_root(), help="repository root")
    parser.add_argument("--skip-compose", action="store_true", help="skip docker compose config rendering")
    parser.add_argument(
        "--write-postgres-secret",
        action="store_true",
        help="write deploy/secrets/postgres_password from POSTGRES_PASSWORD",
    )
    parser.add_argument("--force", action="store_true", help="overwrite deploy/secrets/postgres_password when writing")
    args = parser.parse_args(argv)

    errors = run_preflight(
        args.root.resolve(),
        skip_compose=args.skip_compose,
        write_secret=args.write_postgres_secret,
        force=args.force,
    )
    if errors:
        print("Hosted POC preflight failed; review the hosted POC environment and compose overlays.", file=sys.stderr)
        return 1
    print("Hosted POC preflight passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
