import { expect, it } from "vitest";
import { FLOW_NODE_TYPES } from "@/lib/graph-entity-mapping";
import { NODE_LABELS } from "@/lib/entity-labels";
import { LINEAGE_NODE_GRAPH_KIND } from "@/lib/graph-utils";

// Preserve the public mapping contract while replacing duplicate tables.
it("preserves every existing FLOW_NODE_TYPES mapping", () => {
  expect(FLOW_NODE_TYPES).toEqual({
  "provider": "providerNode",
  "agent": "agentNode",
  "org": "providerNode",
  "account": "providerNode",
  "user": "userNode",
  "group": "groupNode",
  "role": "credentialNode",
  "policy": "credentialNode",
  "serviceAccount": "serviceAccountNode",
  "servicePrincipal": "serviceAccountNode",
  "federatedIdentity": "serviceAccountNode",
  "environment": "environmentNode",
  "fleet": "fleetNode",
  "cluster": "clusterNode",
  "server": "serverNode",
  "sharedServer": "sharedServerNode",
  "package": "packageNode",
  "vulnerability": "vulnNode",
  "credential": "credentialNode",
  "tool": "toolNode",
  "model": "modelNode",
  "framework": "frameworkNode",
  "dataset": "datasetNode",
  "container": "containerNode",
  "cloudResource": "cloudResourceNode",
  "misconfiguration": "misconfigNode",
  "managedIdentity": "managedIdentityNode",
  "accessGrant": "accessGrantNode",
  "accessPolicy": "accessPolicyNode",
  "driftIncident": "driftIncidentNode",
  "dataStore": "dataStoreNode",
  "directory": "containerNode",
  "sourceFile": "packageNode",
  "configFile": "packageNode",
  "codeModule": "packageNode",
  "ciJob": "toolNode",
  "apiGateway": "cloudResourceNode",
  "toolCall": "toolNode",
  "blueprint": "accessPolicyNode"
});
});
it("preserves every existing NODE_LABELS mapping", () => {
  expect(NODE_LABELS).toEqual({
  "provider": "Provider",
  "agent": "Agent",
  "org": "Organization",
  "account": "Account",
  "user": "User",
  "group": "Group",
  "role": "Role",
  "policy": "Policy",
  "serviceAccount": "Service Account",
  "servicePrincipal": "Service Principal",
  "federatedIdentity": "Federated Identity",
  "environment": "Environment",
  "fleet": "Fleet",
  "cluster": "Cluster",
  "server": "Server",
  "sharedServer": "Shared Server",
  "package": "Package",
  "vulnerability": "Vulnerability",
  "credential": "Credential",
  "tool": "Tool",
  "model": "Model",
  "framework": "Framework",
  "dataset": "Dataset",
  "container": "Container",
  "cloudResource": "Cloud Resource",
  "misconfiguration": "Misconfiguration",
  "managedIdentity": "Managed Identity",
  "accessGrant": "Access Grant",
  "accessPolicy": "Access Policy",
  "driftIncident": "Drift Incident",
  "dataStore": "Data Store",
  "directory": "Directory",
  "sourceFile": "Source File",
  "configFile": "Config File",
  "codeModule": "Code Module",
  "ciJob": "CI/CD Job",
  "apiGateway": "API Gateway",
  "toolCall": "Tool Call",
  "blueprint": "Blueprint"
});
});
it("preserves every existing LINEAGE_NODE_GRAPH_KIND mapping", () => {
  expect(LINEAGE_NODE_GRAPH_KIND).toEqual({
  "provider": "provider",
  "agent": "agent",
  "server": "server",
  "sharedServer": "server",
  "package": "package",
  "vulnerability": "vulnerability",
  "misconfiguration": "misconfiguration",
  "credential": "credential",
  "tool": "tool",
  "model": "model",
  "framework": "framework",
  "dataset": "dataset",
  "container": "container",
  "cloudResource": "cloud_resource",
  "org": "org",
  "account": "account",
  "user": "user",
  "group": "group",
  "role": "role",
  "policy": "policy",
  "serviceAccount": "service_account",
  "servicePrincipal": "service_principal",
  "federatedIdentity": "federated_identity",
  "environment": "environment",
  "fleet": "fleet",
  "cluster": "cluster",
  "managedIdentity": "managed_identity",
  "accessGrant": "access_grant",
  "accessPolicy": "access_policy",
  "driftIncident": "drift_incident",
  "dataStore": "data_store",
  "directory": "directory",
  "sourceFile": "source_file",
  "configFile": "config_file",
  "codeModule": "code_module",
  "ciJob": "ci_job",
  "apiGateway": "api_gateway",
  "toolCall": "tool_call",
  "blueprint": "blueprint"
});
});
