import type { LineageNodeType } from "@/lib/entity-icons";

export const NODE_LABELS: Record<LineageNodeType, string> = {
  provider: "Provider",
  agent: "Agent",
  org: "Organization",
  account: "Account",
  user: "User",
  group: "Group",
  role: "Role",
  policy: "Policy",
  serviceAccount: "Service Account",
  servicePrincipal: "Service Principal",
  federatedIdentity: "Federated Identity",
  environment: "Environment",
  fleet: "Fleet",
  cluster: "Cluster",
  server: "Server",
  sharedServer: "Shared Server",
  package: "Package",
  vulnerability: "Vulnerability",
  credential: "Credential",
  tool: "Tool",
  model: "Model",
  framework: "Framework",
  dataset: "Dataset",
  container: "Container",
  cloudResource: "Cloud Resource",
  misconfiguration: "Misconfiguration",
  managedIdentity: "Managed Identity",
  accessGrant: "Access Grant",
  accessPolicy: "Access Policy",
  driftIncident: "Drift Incident",
  dataStore: "Data Store",
  directory: "Directory",
  sourceFile: "Source File",
  configFile: "Config File",
  codeModule: "Code Module",
  ciJob: "CI/CD Job",
  apiGateway: "API Gateway",
  toolCall: "Tool Call",
  blueprint: "Blueprint",
};

