#!/usr/bin/env python3
"""Export the FastAPI OpenAPI contract as committed SDK input artifacts.

Usage:

    python scripts/export_openapi.py
    python scripts/export_openapi.py --check

The generated artifacts are intentionally committed. They are the stable
control-plane contract that SDK codegen can consume without importing the app.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
OPENAPI_DIR = ROOT / "docs" / "openapi"
OPENAPI_JSON = OPENAPI_DIR / "v1.json"
OPENAPI_YAML = OPENAPI_DIR / "v1.yaml"
OPENAPI_OWNED_SUFFIXES = {".json", ".yaml", ".yml"}


def _openapi_schema() -> dict[str, Any]:
    # Exporting the schema imports the API app but does not start a server. A
    # stable local key keeps import-time audit logging quiet for this contract
    # generation path without affecting runtime configuration.
    os.environ.setdefault("AGENT_BOM_AUDIT_HMAC_KEY", "openapi-export-local-contract-key")
    from agent_bom.api.server import app

    app.openapi_schema = None
    schema = app.openapi()
    if not isinstance(schema, dict):
        raise RuntimeError("FastAPI returned a non-object OpenAPI schema")
    return schema


def _render_json(schema: dict[str, Any]) -> str:
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def _render_yaml(schema: dict[str, Any]) -> str:
    return yaml.safe_dump(schema, sort_keys=True, allow_unicode=False)


def _pending_artifacts() -> list[tuple[Path, str]]:
    schema = _openapi_schema()
    return [
        (OPENAPI_JSON, _render_json(schema)),
        (OPENAPI_YAML, _render_yaml(schema)),
    ]


def _diff_message(path: Path, expected: str) -> str | None:
    if not path.exists():
        return f"missing: {path.relative_to(ROOT)}"
    actual = path.read_text(encoding="utf-8")
    if actual != expected:
        return f"drift: {path.relative_to(ROOT)} differs from generated OpenAPI"
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when committed OpenAPI artifacts diverge from the app.",
    )
    args = parser.parse_args()

    pending = _pending_artifacts()
    if args.check:
        problems = [problem for path, content in pending if (problem := _diff_message(path, content))]
        expected_paths = {path for path, _ in pending}
        if OPENAPI_DIR.exists():
            for existing in OPENAPI_DIR.iterdir():
                if existing.is_file() and existing.suffix in OPENAPI_OWNED_SUFFIXES and existing not in expected_paths:
                    problems.append(f"stale: {existing.relative_to(ROOT)} is not generated by scripts/export_openapi.py")
        if problems:
            print("docs/openapi/ is out of sync with agent_bom.api.server.app:", file=sys.stderr)
            for problem in problems:
                print(f"  - {problem}", file=sys.stderr)
            print("Run `python scripts/export_openapi.py` to refresh the OpenAPI artifacts.", file=sys.stderr)
            return 1
        print("OK: docs/openapi/ matches agent_bom.api.server.app")
        return 0

    OPENAPI_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for path, content in pending:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
            written += 1
    print(f"Wrote {written} OpenAPI artifact(s) under docs/openapi/.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
