#!/usr/bin/env python3
"""Generate docs/AGENT_CAPABILITY.md — machine-readable product card for agents."""

from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
METRICS_JSON = ROOT / "docs" / "PRODUCT_METRICS.json"
OUT = ROOT / "docs" / "AGENT_CAPABILITY.md"


def _version() -> str:
    text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    match = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    return match.group(1) if match else "unknown"


def _metric(metrics: list[dict], name: str) -> int | str:
    for row in metrics:
        if row.get("name") == name:
            return row.get("value", "—")
    return "—"


def _rest_surface() -> tuple[int, int, int]:
    """Count REST operations, route modules, and WebSocket routes from the
    committed OpenAPI contract and route source so this card never drifts."""
    operations = 0
    openapi = ROOT / "docs" / "openapi" / "v1.json"
    if openapi.exists():
        spec = json.loads(openapi.read_text(encoding="utf-8"))
        methods = {"get", "post", "put", "patch", "delete", "head", "options"}
        operations = sum(1 for item in spec.get("paths", {}).values() for m in item if m.lower() in methods)
    routes_dir = ROOT / "src" / "agent_bom" / "api" / "routes"
    route_modules = 0
    ws_routes = 0
    if routes_dir.exists():
        route_modules = len([f for f in routes_dir.glob("*.py") if f.name != "__init__.py"])
        for f in routes_dir.glob("*.py"):
            ws_routes += len(re.findall(r"\.websocket\(", f.read_text(encoding="utf-8")))
    return operations, route_modules, ws_routes


def render(snapshot: dict) -> str:
    metrics = snapshot.get("metrics", [])
    version = snapshot.get("version") or _version()
    mcp_tools = _metric(metrics, "MCP tools")
    mcp_resources = _metric(metrics, "MCP resources")
    mcp_prompts = _metric(metrics, "MCP prompts")
    ecosystems = _metric(metrics, "Supported package ecosystems")
    proxy_detectors = _metric(metrics, "Proxy inline detectors")
    rest_operations, rest_route_modules, rest_ws_routes = _rest_surface()

    return f"""# agent-bom — agent capability manifest

<!-- Generated by scripts/generate_agent_capability_manifest.py on {date.today().isoformat()} -->

Open security scanner and **self-hosted control plane** for AI/MCP infrastructure.
Not a managed MCP connector catalog. Primary wedge: scan → graph → prove path → enforce on selected runtime hops.

## Description

`agent-bom` inventories agents, MCP servers, packages, credentials, and cloud
estate into one evidence model (`Finding` + `ContextGraph`). Humans use CLI, API,
and dashboard; AI clients use strict-argument MCP tools over the same findings,
attack paths, compliance tags, and runtime audit chain.

## Capabilities

| Area | Shipped today |
|---|---|
| MCP security tools | {mcp_tools} tools, {mcp_resources} resources, {mcp_prompts} workflow prompts |
| REST API | {rest_operations} operations across {rest_route_modules} route modules (+ {rest_ws_routes} WebSocket routes) — see `docs/openapi/v1.json` |
| Package / SCA | {ecosystems} ecosystems, SARIF, CycloneDX, SPDX, HTML |
| Graph / blast radius | UnifiedGraph, attack paths, hop counts, remediation handoff |
| Runtime proxy | stdio/local MCP inline enforcement ({proxy_detectors} detectors) |
| Runtime gateway | shared HTTP/SSE MCP relay, policy-as-code, live feed + KPI rollup |
| Fleet inventory | endpoint MCP configs, transports, declared tools, credential refs |
| Auth | API keys, OAuth AS, OIDC shim, SAML (optional extra), SCIM provisioning |
| Audit | signed audit chain, gateway feed, identity lifecycle |
| Deployment | CLI, Docker, GitHub Action, Helm/EKS, airgap — customer VPC |

## Not shipped / honest boundaries

- No managed multi-tenant SaaS (`agent-bom Cloud` is roadmap-only).
- No 1,000+ verified MCP app connectors — govern **your** upstream MCP servers via proxy/gateway.
- No Cedar policy engine — YAML/conditional rules + firewall plugins (see `docs/archive/ROADMAP_QUICK_WINS.md`).
- No turnkey CrowdStrike/SIEM tiles — OCSF/OTLP export hooks; operator wires SIEM.

## Runtime surfaces

| Surface | Command / route | Use when |
|---|---|---|
| Local MCP proxy | `agent-bom proxy …` | stdio MCP on laptop or sidecar |
| Shared gateway | `agent-bom gateway serve` / `/v1/gateway/*` | remote HTTP/SSE MCP traffic plane |
| Gateway KPIs | `GET /v1/gateway/feed/kpis` | calls today, blocked, shadow AI, data filters |
| Gateway feed | `GET /v1/gateway/feed` | per-agent tool-call authorization stream |
| Control plane UI | `/gateway?capture=1` | operator cockpit |

## Endpoints and resources

| Resource | Location |
|---|---|
| Docs site | https://msaad00.github.io/agent-bom/ |
| OpenAPI | `docs/openapi/v1.json` |
| MCP server | `agent-bom mcp server` |
| First run | `docs/FIRST_RUN.md` |
| Product boundaries | `docs/PRODUCT_BOUNDARIES.md` |
| Helm chart | `deploy/helm/agent-bom/` |

## Version

`{version}` — regenerate metrics with `python scripts/product_metrics_snapshot.py --write` and this file with `python scripts/generate_agent_capability_manifest.py --write`.
"""


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="Write docs/AGENT_CAPABILITY.md")
    parser.add_argument("--check", action="store_true", help="Fail if manifest is stale")
    args = parser.parse_args()

    if METRICS_JSON.exists():
        snapshot = json.loads(METRICS_JSON.read_text(encoding="utf-8"))
    else:
        snapshot = {"version": _version(), "metrics": []}

    content = render(snapshot) + "\n"
    if args.write:
        OUT.write_text(content, encoding="utf-8")
        print(f"wrote {OUT}")
        return

    if args.check:
        if not OUT.exists():
            raise SystemExit(f"missing {OUT}")
        if OUT.read_text(encoding="utf-8") != content:
            raise SystemExit(f"stale {OUT} — run python scripts/generate_agent_capability_manifest.py --write")
        print(f"ok {OUT}")
        return

    print(content)


if __name__ == "__main__":
    main()
