#!/usr/bin/env python3
"""Regenerate the generated section of docs/DATA_MODEL.md.

Usage:
    python scripts/regenerate_data_model_atlas.py
    python scripts/regenerate_data_model_atlas.py --check
"""

from __future__ import annotations

import argparse
import dataclasses
import enum
import json
import sys
from pathlib import Path
from typing import Any, get_args, get_origin

ROOT = Path(__file__).resolve().parents[1]
DOC_PATH = ROOT / "docs" / "DATA_MODEL.md"
START = "<!-- DATA_MODEL_ATLAS:START -->"
END = "<!-- DATA_MODEL_ATLAS:END -->"


def _bootstrap_imports() -> None:
    src_path = str(ROOT / "src")
    if src_path not in sys.path:
        sys.path.insert(0, src_path)


def _type_name(value: Any) -> str:
    origin = get_origin(value)
    if origin is not None:
        args = ", ".join(_type_name(arg) for arg in get_args(value))
        name = getattr(origin, "__name__", str(origin).replace("typing.", ""))
        return f"{name}[{args}]" if args else name
    if hasattr(value, "__name__"):
        return value.__name__
    text = str(value).replace("typing.", "")
    return text.replace("<class '", "").replace("'>", "")


def _enum_values(cls: type[enum.Enum]) -> str:
    return ", ".join(f"`{item.value}`" for item in cls)


def _dataclass_row(cls: type[Any]) -> str:
    fields = [f"`{field.name}: {_type_name(field.type)}`" for field in dataclasses.fields(cls)]
    return f"| `{cls.__name__}` | {len(fields)} | {', '.join(fields)} |"


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def render_generated_section() -> str:
    _bootstrap_imports()

    from agent_bom import models
    from agent_bom.graph.types import EntityType, RelationshipType

    inventory_schema = _load_json(ROOT / "config" / "schemas" / "inventory.schema.json")
    openapi_path = ROOT / "docs" / "openapi" / "v1.json"
    openapi = _load_json(openapi_path) if openapi_path.exists() else {"paths": {}, "components": {"schemas": {}}}

    dataclass_names = [
        "Vulnerability",
        "PackageOccurrence",
        "Package",
        "MCPTool",
        "MCPResource",
        "PermissionProfile",
        "MCPServer",
        "Agent",
        "BlastRadius",
        "AIBOMReport",
    ]
    dataclass_rows = [_dataclass_row(getattr(models, name)) for name in dataclass_names]

    agent_type_enum = inventory_schema["$defs"]["Agent"]["properties"]["agent_type"].get("enum", [])
    package_ecosystems = inventory_schema["$defs"]["Package"]["oneOf"][1]["properties"]["ecosystem"].get("enum", [])
    transport_enum = inventory_schema["$defs"]["MCPServer"]["properties"]["transport"].get("enum", [])
    root_required = inventory_schema.get("required", [])

    paths = openapi.get("paths", {})
    component_schemas = openapi.get("components", {}).get("schemas", {})

    lines = [
        START,
        "",
        "## Generated Data Model Index",
        "",
        "> Generated by `python scripts/regenerate_data_model_atlas.py`. Run with `--check` in CI or before release claims.",
        "",
        "### Canonical Dataclasses",
        "",
        "| Class | Field count | Fields |",
        "|---|---:|---|",
        *dataclass_rows,
        "",
        "### Canonical Enums",
        "",
        "| Enum | Count | Values |",
        "|---|---:|---|",
        f"| `Severity` | {len(models.Severity)} | {_enum_values(models.Severity)} |",
        f"| `AgentType` | {len(models.AgentType)} | {_enum_values(models.AgentType)} |",
        f"| `TransportType` | {len(models.TransportType)} | {_enum_values(models.TransportType)} |",
        f"| `ServerSurface` | {len(models.ServerSurface)} | {_enum_values(models.ServerSurface)} |",
        f"| `AgentStatus` | {len(models.AgentStatus)} | {_enum_values(models.AgentStatus)} |",
        f"| `EntityType` | {len(EntityType)} | {_enum_values(EntityType)} |",
        f"| `RelationshipType` | {len(RelationshipType)} | {_enum_values(RelationshipType)} |",
        "",
        "### Live Schema Cross-Checks",
        "",
        "| Schema | Check | Value |",
        "|---|---|---:|",
        f"| `config/schemas/inventory.schema.json` | root required fields | `{', '.join(root_required)}` |",
        f"| `config/schemas/inventory.schema.json` | `Agent.agent_type` enum values | {len(agent_type_enum)} |",
        f"| `config/schemas/inventory.schema.json` | `Package.ecosystem` enum values | {len(package_ecosystems)} |",
        f"| `config/schemas/inventory.schema.json` | `MCPServer.transport` enum values | {len(transport_enum)} |",
        f"| `docs/openapi/v1.json` | paths | {len(paths)} |",
        f"| `docs/openapi/v1.json` | component schemas | {len(component_schemas)} |",
        "",
        END,
    ]
    return "\n".join(lines)


def replace_section(document: str, generated: str) -> str:
    if START not in document or END not in document:
        raise SystemExit(f"{DOC_PATH} is missing {START}/{END} markers")
    before = document.split(START, 1)[0].rstrip()
    after = document.split(END, 1)[1].lstrip()
    return f"{before}\n\n{generated}\n\n{after}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if docs/DATA_MODEL.md is not regenerated")
    args = parser.parse_args()

    current = DOC_PATH.read_text(encoding="utf-8")
    generated = render_generated_section()
    updated = replace_section(current, generated)

    if args.check:
        if current != updated:
            print(f"{DOC_PATH} is stale; run python scripts/regenerate_data_model_atlas.py", file=sys.stderr)
            return 1
        return 0

    DOC_PATH.write_text(updated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
