"""Auth command group — guided SSO / OIDC onboarding.

This wraps the *existing* OIDC mechanism with a setup wizard. It never forks the
auth logic: it only COLLECTS, VALIDATES, and EMITS the ``AGENT_BOM_OIDC_*``
configuration a self-hoster needs to turn on browser SSO ("Sign in with Google"
or any OIDC issuer). The bearer/verification path lives in
``agent_bom.api.oidc`` and the auth-code + PKCE browser path in
``agent_bom.api.oidc_browser`` — both untouched here.

Usage::

    agent-bom auth setup-oidc                      # interactive wizard (TTY)
    agent-bom auth setup-oidc --provider google \\
        --client-id … --client-secret … --base-url https://abom.example --write
"""

from __future__ import annotations

import sys
from collections import OrderedDict
from pathlib import Path
from typing import Optional

import click

from agent_bom.cli._grouped_help import SuggestingGroup

# The dashboard callback route is mounted under the versioned API prefix
# (``/v1/auth/oidc/callback`` in ``routes/enterprise.py``). Kept as a literal so
# the CLI import stays light (no FastAPI import); ``test_auth_setup_oidc`` asserts
# it still matches ``API_V1_PREFIX + "/auth/oidc/callback"`` so drift is caught.
OIDC_CALLBACK_PATH = "/v1/auth/oidc/callback"

# Default env-file target. 0644 (see ``write_env_file``) because the compose
# stack mounts this as an ``env_file`` read by a non-root container UID.
DEFAULT_ENV_PATH = "deploy/secrets/oidc.env"

_PROVIDER_ISSUERS = {
    "google": "https://accounts.google.com",
}


class OIDCSetupError(click.ClickException):
    """Raised for a user-correctable wizard configuration error."""


def _stdin_is_tty() -> bool:
    """Whether stdin is an interactive terminal (patch point for tests)."""
    try:
        return sys.stdin.isatty()
    except (ValueError, OSError):
        return False


# ── Pure config builders (unit-tested directly) ─────────────────────────────


def derive_redirect_uri(base_url: str) -> str:
    """Derive the IdP redirect URI from the deployment base URL.

    The IdP must allowlist exactly this value; it maps to the dashboard's
    auth-code callback route.
    """
    base = base_url.strip().rstrip("/")
    if not base:
        raise OIDCSetupError("Base URL is required to derive the redirect URI.")
    from urllib.parse import urlparse

    parsed = urlparse(base)
    if parsed.scheme not in {"https", "http"} or not parsed.netloc:
        raise OIDCSetupError(f"Base URL must be an absolute http(s) URL, got: {base_url!r}")
    return f"{base}{OIDC_CALLBACK_PATH}"


def build_oidc_env(
    *,
    issuer: str,
    client_id: str,
    redirect_uri: str,
    client_secret: Optional[str] = None,
    audience: Optional[str] = None,
    role_claim: Optional[str] = None,
    tenant_claim: Optional[str] = None,
) -> "OrderedDict[str, str]":
    """Build the ordered ``AGENT_BOM_OIDC_*`` env mapping for browser SSO.

    Encodes the two conventions verified against the mechanism:

    - **audience** defaults to ``client_id`` — the browser auth-code ID token's
      ``aud`` claim is the OAuth client ID (Google and the OIDC core spec), and
      ``AGENT_BOM_OIDC_AUDIENCE`` is required whenever OIDC is enabled.
    - when **no tenant claim** is configured this is a single-tenant self-host,
      so ``AGENT_BOM_OIDC_ALLOW_DEFAULT_TENANT=1`` is emitted; otherwise the
      fail-closed multi-tenant default would block login for IdPs (e.g. Google)
      that emit no tenant claim. Surfaced explicitly, never silent.
    """
    issuer = (issuer or "").strip()
    client_id = (client_id or "").strip()
    redirect_uri = (redirect_uri or "").strip()
    if not issuer:
        raise OIDCSetupError("OIDC issuer is required (e.g. https://accounts.google.com).")
    if not client_id:
        raise OIDCSetupError("OIDC client ID is required.")
    if not redirect_uri:
        raise OIDCSetupError("Redirect URI is required (pass --base-url or --redirect-uri).")

    env: "OrderedDict[str, str]" = OrderedDict()
    env["AGENT_BOM_OIDC_ISSUER"] = issuer
    env["AGENT_BOM_OIDC_CLIENT_ID"] = client_id
    secret = (client_secret or "").strip()
    if secret:
        env["AGENT_BOM_OIDC_CLIENT_SECRET"] = secret
    env["AGENT_BOM_OIDC_REDIRECT_URI"] = redirect_uri
    env["AGENT_BOM_OIDC_AUDIENCE"] = (audience or "").strip() or client_id
    role = (role_claim or "").strip()
    if role:
        env["AGENT_BOM_OIDC_ROLE_CLAIM"] = role
    tenant = (tenant_claim or "").strip()
    if tenant:
        env["AGENT_BOM_OIDC_TENANT_CLAIM"] = tenant
    else:
        env["AGENT_BOM_OIDC_ALLOW_DEFAULT_TENANT"] = "1"
    return env


def render_env_block(env: "OrderedDict[str, str]") -> str:
    """Render the env mapping as a copy-paste dotenv block (no shell wrapping)."""
    lines = [
        "# agent-bom OIDC browser SSO — generated by `agent-bom auth setup-oidc`",
        "# Load as a docker-compose env_file, or export into the API process env.",
    ]
    lines.extend(f"{key}={value}" for key, value in env.items())
    return "\n".join(lines) + "\n"


def write_env_file(path: str | Path, block: str) -> Path:
    """Write the env block to ``path`` with mode 0644.

    0644 (not 0400) is deliberate: the compose stack mounts this file as an
    ``env_file`` and the API container runs as a non-root UID that must read it
    at start; owner-only bits break that mount. Protect the *directory*, not the
    file bits. The caller must confirm before writing — this never runs silently.
    """
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(block, encoding="utf-8")
    target.chmod(0o644)
    return target


def check_issuer_connectivity(issuer: str) -> dict[str, object]:
    """Reuse the mechanism's discovery to confirm the issuer's endpoints resolve.

    Returns a result dict; never raises. Reuses ``oidc.discover_oidc`` (the same
    ``.well-known/openid-configuration`` fetch + validation the auth path uses)
    so the wizard does not fork a second discovery fetcher. An unreachable issuer
    is a warning (``reachable=False``), not a failure, so an offline operator can
    still emit config.
    """
    from agent_bom.api.oidc import OIDCError, discover_oidc

    try:
        doc = discover_oidc(issuer)
    except OIDCError as exc:
        return {"reachable": False, "complete": False, "warning": str(exc)}
    endpoints = {key: str(doc.get(key) or "").strip() for key in ("authorization_endpoint", "token_endpoint", "jwks_uri")}
    missing = [key for key, value in endpoints.items() if not value]
    result: dict[str, object] = {"reachable": True, "complete": not missing, **endpoints}
    if missing:
        result["missing"] = missing
    return result


# ── Provider-side steps (operator guidance) ─────────────────────────────────


def _provider_steps(provider: str, redirect_uri: str) -> list[str]:
    if provider == "google":
        return [
            "Google Cloud Console → APIs & Services → Credentials.",
            "Create Credentials → OAuth client ID → Application type: Web application.",
            f"Add an Authorized redirect URI, exactly:  {redirect_uri}",
            "Create, then copy the Client ID and Client secret shown.",
        ]
    return [
        "Open your IdP's app/client registration (Okta, Entra ID, Auth0, Keycloak…).",
        "Create an OIDC/OAuth2 'Web application' client using the authorization-code flow.",
        f"Set the redirect/callback URI exactly to:  {redirect_uri}",
        "Copy the issuer URL, client ID, and (for confidential clients) client secret.",
    ]


# ── Click group + command ───────────────────────────────────────────────────


@click.group("auth", cls=SuggestingGroup)
def auth_group() -> None:
    """Authentication setup helpers — guided SSO / OIDC onboarding.

    Collects, validates, and emits the ``AGENT_BOM_OIDC_*`` configuration for
    browser SSO. It wraps the existing OIDC mechanism (bearer verification +
    auth-code/PKCE) and never stores a secret or changes token validation.

    \b
    Subcommands:
      setup-oidc   Guided "Sign in with Google" / OIDC browser-SSO setup
    """


@click.command("setup-oidc")
@click.option("--provider", type=click.Choice(["google", "generic"]), default=None, help="IdP preset (google fills the issuer).")
@click.option("--issuer", default=None, help="OIDC issuer URL, e.g. https://accounts.google.com.")
@click.option("--client-id", default=None, help="OAuth client ID from the IdP.")
@click.option("--client-secret", default=None, help="OAuth client secret (omit for a PKCE public client).")
@click.option("--base-url", default=None, help="Deployment base URL; the redirect URI is derived from it.")
@click.option("--redirect-uri", default=None, help="Override the derived redirect URI (must match the IdP allowlist).")
@click.option("--audience", default=None, help="Expected JWT audience (defaults to the client ID).")
@click.option("--role-claim", default=None, help="JWT claim to map to a role (default agent_bom_role).")
@click.option("--tenant-claim", default=None, help="JWT claim to map to a tenant (omit for single-tenant self-host).")
@click.option("--write", "do_write", is_flag=True, help="Write the env block to --output without prompting.")
@click.option("--output", "-o", "output_path", default=DEFAULT_ENV_PATH, show_default=True, help="Env-file path to write.")
@click.option("--non-interactive", "--yes", "-y", "non_interactive", is_flag=True, help="Never prompt; require flags.")
def setup_oidc_cmd(
    provider: Optional[str],
    issuer: Optional[str],
    client_id: Optional[str],
    client_secret: Optional[str],
    base_url: Optional[str],
    redirect_uri: Optional[str],
    audience: Optional[str],
    role_claim: Optional[str],
    tenant_claim: Optional[str],
    do_write: bool,
    output_path: str,
    non_interactive: bool,
) -> None:
    """Guided setup for browser SSO ("Sign in with Google" or any OIDC issuer).

    Prints the provider-side steps, validates the issuer's discovery document,
    and emits a copy-paste ``AGENT_BOM_OIDC_*`` env block. Optionally writes it
    to a file. Reuses the existing OIDC mechanism; nothing here changes token
    validation or stores a secret.
    """
    from rich.console import Console

    con = Console()
    interactive = (not non_interactive) and _stdin_is_tty()

    if not provider:
        if interactive:
            provider = "google" if click.confirm("Use the Google preset?", default=True) else "generic"
        else:
            provider = "generic"

    # Issuer.
    if not issuer:
        default_issuer = _PROVIDER_ISSUERS.get(provider, "")
        if interactive:
            issuer = click.prompt("OIDC issuer URL", default=default_issuer or None)
        else:
            issuer = default_issuer
    if not issuer:
        raise OIDCSetupError("Missing --issuer (required for a generic provider). Re-run with --issuer or --provider google.")

    # Client ID.
    if not client_id and interactive:
        client_id = click.prompt("OAuth client ID")
    if not client_id:
        raise OIDCSetupError("Missing --client-id.")

    # Client secret (optional; never echoed).
    if client_secret is None and interactive:
        client_secret = click.prompt("OAuth client secret (blank = PKCE public client)", default="", hide_input=True, show_default=False)

    # Redirect URI (from base URL, or explicit override).
    if not redirect_uri:
        if not base_url and interactive:
            base_url = click.prompt("Deployment base URL (e.g. https://abom.example.com)")
        if base_url:
            redirect_uri = derive_redirect_uri(base_url)
    if not redirect_uri:
        raise OIDCSetupError("Missing redirect URI. Pass --base-url or --redirect-uri.")

    # Audience (defaults to client ID).
    if not audience and interactive:
        audience = click.prompt("Expected JWT audience", default=client_id)

    env = build_oidc_env(
        issuer=issuer,
        client_id=client_id,
        redirect_uri=redirect_uri,
        client_secret=client_secret,
        audience=audience,
        role_claim=role_claim,
        tenant_claim=tenant_claim,
    )

    # Connectivity check (warn, never fail).
    con.print(f"\n  [bold]OIDC setup[/bold] [dim]· provider {provider} · issuer {issuer}[/dim]")
    check = check_issuer_connectivity(issuer)
    if check.get("reachable") and check.get("complete"):
        con.print("  [green]Issuer discovery OK[/green] [dim]· authorization, token, and JWKS endpoints resolved.[/dim]")
    elif check.get("reachable"):
        con.print(f"  [yellow]Issuer reachable but incomplete[/yellow] [dim]· missing {', '.join(check.get('missing', []))}.[/dim]")  # type: ignore[arg-type]
    else:
        con.print(f"  [yellow]Could not reach issuer discovery[/yellow] [dim]· {check.get('warning', '')}[/dim]")
        con.print("  [dim]Continuing offline — the env block below is still valid; verify the issuer URL.[/dim]")

    # Provider-side steps.
    con.print("\n  [bold]1. Register the client with your IdP[/bold]")
    for i, step in enumerate(_provider_steps(provider, redirect_uri), start=1):
        con.print(f"     [cyan]{i}.[/cyan] {step}")

    # Env block (the one place the secret is shown).
    con.print("\n  [bold]2. Configuration[/bold] [dim]· set these on the agent-bom API process[/dim]")
    if tenant_claim:
        con.print("  [dim]Multi-tenant: tenant is read from the configured claim.[/dim]")
    else:
        con.print("  [dim]Single-tenant self-host: all SSO users share the default tenant (ALLOW_DEFAULT_TENANT=1).[/dim]")
    block = render_env_block(env)
    click.echo("")
    click.echo(block)

    # Write (only on --write or explicit confirmation; never silent).
    should_write = do_write
    if not should_write and interactive:
        should_write = click.confirm(f"Write this block to {output_path}?", default=False)
    if should_write:
        written = write_env_file(output_path, block)
        con.print(f"  [green]Wrote[/green] {written} [dim]· mode 0644 (compose env_file readable)[/dim]")
        if "AGENT_BOM_OIDC_CLIENT_SECRET" in env:
            con.print(
                f"  [yellow]Contains a client secret[/yellow] [dim]· restrict the {written.parent}/ directory; do not commit it.[/dim]"
            )
    else:
        con.print(f"  [dim]Not written. Re-run with --write to save to {output_path}.[/dim]")

    con.print("\n  [bold]3. Restart the API[/bold] [dim]· then open the dashboard /login → 'Sign in with SSO'.[/dim]\n")


auth_group.add_command(setup_oidc_cmd, "setup-oidc")
